import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

await mkdir('work',{recursive:true});
await build({entryPoints:['lib/device-store.ts'],bundle:true,platform:'node',format:'esm',outfile:'work/device-store.js',external:['sql.js']});
const {openDeviceStore}=await import('../work/device-store.js');
const wasm=path.join(path.dirname(fileURLToPath(import.meta.url)),'..','node_modules','sql.js','dist','sql-wasm.wasm');
const store=await openDeviceStore(undefined,()=>{},()=>wasm);
const contacts=[{name:'Contacto',role:'Administración',phone:'3000000000',email:'contacto@finca.test',receiveReports:true}];
const farm=store.changeTeam({op:'create',name:'Finca Prueba',zone:'Sabana',contacts});
const person=store.changeTeam({op:'addLocal',farmId:farm.id,name:'Ingeniera'});
const request=store.saveRequest({id:'',revision:0,farmId:farm.id,kind:'training',reason:'Capacitación',date:'2026-09-08',rtc:'',assignee:person.id,status:'scheduled'});
const visit=store.saveVisit({id:'',revision:0,farmId:farm.id,requestId:request.id,serviceKind:'training',farm:'Finca Prueba',date:'2026-09-08',city:'',zone:'',technician:'Contacto',responsible:'Ingeniera',rtc:'',chapters:[],answers:{},notes:{},recommendations:{},measurements:{},delivery:'',followup:'',conclusion:'Actividad realizada',photos:[],reviewed:true});
assert.equal(visit.farm,'Finca Prueba');
const reportDraft=store.changeReport({op:'create',visitId:visit.id});
assert.equal(reportDraft.status,'draft');
const jpeg=new Uint8Array([255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,217]);
const photo=store.savePhoto(jpeg,farm.id);
assert.ok(photo.id);
assert.equal(store.photo(photo.id).mime,'image/jpeg');
const withPhoto=store.saveVisit({...visit,photos:[{id:photo.id,caption:'Evidencia',chapter:3}]});
const bytes=store.exportBytes();
assert.ok(bytes.length>1000);
store.deleteReport(reportDraft.id);
assert.equal(store.reports(withPhoto.id).versions.length,0);
store.deleteVisit(withPhoto.id);
assert.equal(store.visits().length,0);
assert.throws(()=>store.photo(photo.id),/Fotografía/);
store.deleteRequest(request.id);
assert.equal(store.requests().length,0);
store.deleteFarm(farm.id);
assert.equal(store.team().farms.length,0);
console.log('PASS: local Android/Windows store, reports and photographs');
