import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
await mkdir('work',{recursive:true});
await build({entryPoints:['lib/model.ts','lib/validate.ts','lib/export-word.ts','lib/metric-analysis.ts','lib/metric-definitions.ts','lib/export-metrics-word.ts','lib/export-matrix-excel.ts','lib/export-matrix-csv.ts','lib/import-matrix.ts','lib/native.ts'],bundle:true,platform:'node',format:'esm',outdir:'work',packages:'external'});
const {blankVisit,metrics,issues,catalog,findings,compareVisits,overdue,farmKey,metricStatus,metricTrend,visitMetric,recommendationDraft,MAX_PHOTOS}=await import('../work/model.js');
const {validate}=await import('../work/validate.js');
const {exportWord}=await import('../work/export-word.js');
const {exportFarmMetricsWord}=await import('../work/export-metrics-word.js');
const {exportConsolidatedMatrixExcel}=await import('../work/export-matrix-excel.js');
const {exportConsolidatedMatrixCsv}=await import('../work/export-matrix-csv.js');
const {matrixRowsToVisits}=await import('../work/import-matrix.js');
const {compareFarmBenchmarks,consolidatedMetricAnalysis,farmMetricHistory}=await import('../work/metric-analysis.js');
const {MINIMUM_TREND_POINTS,compareMetricReadings,compareNumericValues,descriptiveTrend,metricDefinition,metricReading,strictNumber}=await import('../work/metric-definitions.js');
const v=blankVisit();assert.equal(metrics(v).total,33);assert.equal(metrics(v).answered,0);
assert.equal(catalog.flatMap(c=>c.items).length,37);assert.equal(catalog[0].items.length,4);assert.equal(catalog[1].items.length,8);
assert.match(recommendationDraft('3.3'),/3\.3/);
Object.assign(v,{farm:'Finca de prueba',technician:'Representante',chapters:[3],reviewed:true});
assert.throws(()=>validate(v),/422/);assert.equal(metrics(v).score,null);
for(const q of catalog[2].items)v.answers[q.id]={value:'SI',observation:'',recommendation:''};
assert.equal(issues(v).length,0);validate(v);
v.answers['3.3']={value:'NO',observation:'Falta de cierre',recommendation:''};assert.equal(metrics(v).findings,1);assert.throws(()=>validate(v),/422/);
v.answers['3.3'].recommendation='Mantener el vehículo cerrado';validate(v);
assert.throws(()=>validate({...v,date:'2026-02-31'}),/Fecha/);
assert.throws(()=>validate({...v,chapters:[3,3]}),/Capítulos/);
assert.throws(()=>validate({...v,serviceKind:{kind:'assurance'}}),/Tipo de servicio/);
assert.throws(()=>validate({...v,photos:[{id:'../private',caption:'',chapter:3}]}),/Fotografía/);
const photoId=n=>'11111111-1111-1111-1111-'+String(n).padStart(12,'0');
assert.throws(()=>validate({...v,photos:Array.from({length:MAX_PHOTOS+1},(_,i)=>({id:photoId(i+1),caption:'',chapter:3}))}),new RegExp('Máximo '+MAX_PHOTOS));
validate({...v,photos:Array.from({length:MAX_PHOTOS},(_,i)=>({id:photoId(i+1),caption:'',chapter:3}))});
assert.equal(metrics({...v,chapters:[4]}).findings,0);
let captured;globalThis.document={createElement(){return {click(){},set href(x){},set download(x){}}}};URL.createObjectURL=blob=>{captured=blob;return 'blob:test'};URL.revokeObjectURL=()=>{};
await exportWord(v);assert.ok(captured.size>5000);await writeFile('work/informe-prueba.docx',Buffer.from(await captured.arrayBuffer()));
console.log('PASS: questionnaire scope, report validation, dates, unsafe photo IDs, Word generation');

const legacy=validate({...v,actions:undefined});assert.deepEqual(legacy.actions,{});
const plan={owner:'Ana',due:'2026-09-10',status:'progress',closure:'',photoId:''};
const planned=validate({...v,actions:{'3.3':plan}});assert.equal(planned.actions['3.3'].owner,'Ana');
assert.equal(overdue(plan,'2026-09-11'),true);assert.equal(overdue(plan,'2026-09-10'),false);
assert.equal(overdue({...plan,status:'closed'},'2026-09-11'),false);
assert.throws(()=>validate({...v,actions:{'3.3':{...plan,status:'closed'}}}),/cerrar/);
assert.throws(()=>validate({...v,actions:{'3.3':{...plan,due:'2026-02-31'}}}),/Fecha/);
assert.throws(()=>validate({...v,actions:{'3.3':{...plan,photoId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'}}}),/evidencia/);
const photo={id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',chapter:3,criterionId:'3.3',caption:'Cierre'};
const closed=validate({...v,photos:[photo],actions:{'3.3':{...plan,status:'closed',closure:'Verificado',photoId:photo.id}}});
assert.equal(findings(closed)[0].action.status,'closed');
assert.equal(findings(closed)[0].action.beforePhotoId,'');
assert.throws(()=>validate({...v,photos:[photo],actions:{'3.3':{...plan,status:'closed',closure:'Verificado',beforePhotoId:photo.id,photoId:photo.id}}}),/distintas/);
const beforePhoto={...photo,id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',caption:'Antes'};
const paired=validate({...v,photos:[beforePhoto,photo],actions:{'3.3':{...plan,status:'closed',closure:'Verificado',beforePhotoId:beforePhoto.id,photoId:photo.id}}});
assert.equal(paired.actions['3.3'].beforePhotoId,beforePhoto.id);
assert.equal(closed.photos[0].criterionId,'3.3');
assert.throws(()=>validate({...v,photos:[{...photo,criterionId:'4.1'}]}),/subcapítulo/);
assert.throws(()=>validate({...closed,photos:[{...photo,chapter:4}]}),/subcapítulo/);
assert.throws(()=>validate({...closed,photos:[{...photo,chapter:4,criterionId:''}]}),/evidencia/);
assert.equal(findings({...planned,chapters:[4]}).length,0);
assert.equal(farmKey('  Finca   Uno '),farmKey('finca uno'));
const now={...v,answers:{...v.answers,'3.3':{value:'SI',observation:'',recommendation:''}}};
assert.equal(compareVisits(v,now)[0].result,'Corregido');
assert.equal(compareVisits(v,v)[0].result,'Recurrente');
assert.equal(compareVisits(v,{...now,chapters:[4]})[0].result,'Sin reevaluar');
assert.equal(compareVisits(v,{...now,answers:{}})[0].result,'Sin reevaluar');
assert.equal(compareVisits(v,{...now,answers:{'3.3':{value:'NA'}}})[0].result,'No aplica');
console.log('PASS: legacy visits, action persistence validation, deadlines, closure evidence, farm matching, comparable history');

assert.equal(overdue({...plan,status:'proposed'},'2026-09-11'),false);
assert.equal(findings({...v,actions:{}})[0].action.status,'proposed');
validate({...v,chapters:[],serviceKind:'training',conclusion:'Capacitación realizada',reviewed:true});
assert.throws(()=>validate({...v,chapters:[],serviceKind:'training',conclusion:'',reviewed:true}),/422/);
console.log('PASS: proposals never overdue and activity reports require results');
const historical={...v,chapters:[1],answers:Object.fromEntries(catalog[0].items.map(q=>[q.id,{value:'SI',observation:'',recommendation:''}]))};
assert.equal(metrics(historical).score,100);assert.equal(metricStatus(85),'acceptable');assert.equal(metricStatus(84),'critical');assert.equal(metricStatus(95),'healthy');
const prior=visitMetric({...historical,date:'2025-01-20'}),current=visitMetric({...historical,date:'2026-01-20',answers:{...historical.answers,'1.4':{value:'NO',observation:'Inventario atrasado',recommendation:'Actualizar'}}});
assert.equal(metricTrend(prior,current),'declined');
console.log('PASS: official chapters one and two plus farm metric status and trend');

const initial={...historical,id:'11111111-1111-1111-1111-111111111111',farm:'Finca Aurora',date:'2024-02-15',reviewed:true};
const followup={...historical,id:'22222222-2222-2222-2222-222222222222',farm:' finca   aurora ',date:'2025-06-15',reviewed:true,answers:{...historical.answers,'1.2':{value:'NO',observation:'Control incompleto',recommendation:'Ajustar control'}}};
const currentFarm={...historical,id:'33333333-3333-3333-3333-333333333333',farm:'FINCA AURORA',date:'2026-08-15',reviewed:true,answers:{...historical.answers,'1.2':{value:'NO',observation:'Control incompleto',recommendation:'Ajustar control'},'1.4':{value:'NO',observation:'Inventario atrasado',recommendation:'Actualizar'}}};
const history=farmMetricHistory([currentFarm,initial,followup],initial.farm);
assert.equal(history.records.length,3);assert.equal(history.latest?.score,50);assert.equal(history.latest?.weightedScore,50);assert.equal(history.latest?.weightedCoveragePct,5);assert.equal(history.latest?.evaluatedChapters,1);assert.equal(history.trend,'declined');assert.equal(history.delta,-50);assert.equal(history.yearly.length,3);assert.equal(history.problems.find(p=>p.id==='1.2')?.occurrences,2);assert.equal(history.chapters[0].findings,2);
const weightedComparison={...historical,farm:'Finca Ponderada',chapters:[1,2],answers:{...Object.fromEntries(catalog[0].items.map(q=>[q.id,{value:'SI'}])),...Object.fromEntries(catalog[1].items.map(q=>[q.id,{value:'NO'}]))}};
const supplemental=farmMetricHistory([weightedComparison],weightedComparison.farm).latest;
assert.equal(supplemental?.score,17);assert.equal(supplemental?.weightedScore,16.7);assert.equal(supplemental?.criteriaCompliance,33.3);assert.equal(supplemental?.weightedCoveragePct,30);
await exportFarmMetricsWord(history);assert.ok(captured.size>3000);
const consolidated=consolidatedMetricAnalysis([initial,followup,currentFarm,{...currentFarm,id:'44444444-4444-4444-4444-444444444444',farm:'Otra finca',date:'2026-09-01',serviceKind:'training'}]);
assert.equal(consolidated.records.length,3);assert.equal(consolidated.farms,1);assert.equal(consolidated.items.find(item=>item.id==='1.2')?.findings,2);assert.equal(consolidated.chapters[0].findings,3);assert.equal(consolidated.matrix.length,12);
const benchmarkA={...initial,id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',farm:'Finca A',date:'2026-09-01',chapters:[1],answers:Object.fromEntries(catalog[0].items.map(q=>[q.id,{value:'SI'}]))};
const benchmarkB={...benchmarkA,id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',farm:'Finca B',date:'2026-09-02',answers:{...benchmarkA.answers,'1.1':{value:'NO',observation:'Hallazgo',recommendation:'Acción'}}};
const benchmarkC={...benchmarkA,id:'cccccccc-cccc-cccc-cccc-cccccccccccc',farm:'Finca C',date:'2026-09-03',chapters:[1,2],answers:{...benchmarkA.answers,...Object.fromEntries(catalog[1].items.map(q=>[q.id,{value:'NO',observation:'Hallazgo',recommendation:'Acción'}]))}};
const benchmarkAmbiguous={...benchmarkA,id:'dddddddd-dddd-dddd-dddd-dddddddddddd',farm:'Finca D',date:'2026-09-04'};
const benchmark={...compareFarmBenchmarks([benchmarkA,{...benchmarkA,date:'2025-09-01',answers:{...benchmarkA.answers,'1.1':{value:'NO'}}},benchmarkB,benchmarkC,benchmarkAmbiguous,{...benchmarkAmbiguous,id:'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'}, {...benchmarkC,id:'ffffffff-ffff-ffff-ffff-ffffffffffff',farm:'Finca capacitación',serviceKind:'training',date:'2026-09-05'}])};
assert.equal(benchmark.groups.length,1);assert.deepEqual(benchmark.groups[0].chapterIds,[1]);assert.deepEqual(benchmark.groups[0].records.map(record=>record.farm),['Finca A','Finca B']);assert.equal(benchmark.groups[0].records[0].rank,1);assert.equal(benchmark.groups[0].records[1].rank,2);assert.equal(benchmark.singleScopes[0].farm,'Finca C');assert.deepEqual(benchmark.ambiguousFarms,['Finca D']);
const benchmarkTie=compareFarmBenchmarks([benchmarkA,{...benchmarkA,id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',farm:'Finca B'}]);
assert.equal(benchmarkTie.groups[0].records[0].rank,1);assert.equal(benchmarkTie.groups[0].records[1].rank,1);assert.equal(benchmarkTie.groups[0].records[0].tied,true);
await exportConsolidatedMatrixExcel(consolidated,'2026-09-09');const matrixBytes=new Uint8Array(await captured.arrayBuffer());assert.equal(String.fromCharCode(...matrixBytes.slice(0,2)),'PK');
await exportConsolidatedMatrixCsv(consolidated,'2026-09-09');assert.match(await captured.text(),/^"Finca";"Fecha";/);
const imported=matrixRowsToVisits([['Finca','Fecha','Responsable AVGUST','Capítulo','Ítem','Respuesta','Hallazgo / observación','Recomendación'],...catalog[0].items.map((question,index)=>['Finca Importada','2025-05-20','Ana',`1. Datos`,question.id,index===1?'No':'Sí',index===1?'Hallazgo histórico':'',index===1?'Recomendación histórica':''])]);
assert.equal(imported.errors.length,0);assert.equal(imported.visits.length,1);assert.equal(imported.visits[0].answers['1.2'].value,'NO');assert.equal(imported.visits[0].reviewed,true);
console.log('PASS: farm history, Excel matrix export and validated historical matrix import');

const ph=metricDefinition('ph'),pressure=metricDefinition('pressure'),compliance=metricDefinition('compliance'),equipment=metricDefinition('equipment');
assert.equal(strictNumber('6,20'),6.2);assert.equal(strictNumber('aprox. diez'),null);assert.equal(strictNumber('30 PSI'),null);assert.equal(strictNumber(''),null);
const measuredA={...initial,measurements:{ph:'6.40',pressure:'30',volume:'0',equipment:'Jacto XP'}};
const measuredB={...followup,measurements:{ph:'6.10',pressure:'32',volume:'2',equipment:'Jacto XP'}};
assert.equal(metricReading(measuredA,ph)?.originalValue,'6.40');assert.equal(metricReading(measuredA,metricDefinition('hardness')),null);assert.equal(metricReading(measuredA,equipment)?.textValue,'Jacto XP');
const phComparison=compareMetricReadings(metricReading(measuredA,ph),metricReading(measuredB,ph),ph);assert.equal(phComparison.change,'decreased');assert.equal(phComparison.delta,-0.3);
const percentage=compareNumericValues(72,81,'%','%',compliance);assert.equal(percentage.delta,9);assert.equal(percentage.relativeChange,12.5);assert.match(percentage.differenceLabel,/puntos porcentuales/);
const zero=compareNumericValues(0,2,'L','L',metricDefinition('volume'));assert.equal(zero.relativeChange,null);assert.equal(zero.change,'increased');
assert.equal(compareNumericValues(30,32,'PSI','bar',pressure).change,'incompatible');assert.equal(compareMetricReadings(metricReading(measuredA,equipment),metricReading(measuredB,equipment),equipment).change,'same');
assert.equal(descriptiveTrend([{numericValue:6.4},{numericValue:6.2}],ph),'insufficient_data');assert.equal(descriptiveTrend([{numericValue:6.4},{numericValue:6.3},{numericValue:6.1}],ph),'decreased');assert.equal(descriptiveTrend([{numericValue:6.4},{numericValue:6.4},{numericValue:6.4}],ph),'stable');assert.equal(MINIMUM_TREND_POINTS,3);
const evolutionSource=await readFile('app/farm-metric-evolution.tsx','utf8');assert.match(evolutionSource,/type="linear"/);assert.doesNotMatch(evolutionSource,/type="monotone"/);assert.match(evolutionSource,/connectNulls=\{false\}/);
console.log('PASS: metric definitions, strict numeric readings, neutral differences, percentage points, trends and linear chart');

const {nativeApp,nativeFiles,saveThroughBridge}=await import('../work/native.js');
const {download}=await import('../work/export-word.js');
assert.equal(nativeApp(),false);assert.equal(nativeFiles(),null);
let transfer={chunks:[]};
const stub=behaviour=>{transfer={chunks:[]};globalThis.AvgustFileBridge={begin(name,mime){transfer.name=name;transfer.mime=mime;return behaviour==='no-space'?'':'token';},append(token,chunk){if(token!=='token'||behaviour==='write-error')return false;transfer.chunks.push(chunk);return true;},finish(token){transfer.finished=token==='token';return behaviour!=='share-error';},abort(){transfer.aborted=true;}};};
const report=new Blob([new Uint8Array(500*1024).fill(65)],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
stub();assert.equal(nativeApp(),true);
await saveThroughBridge(nativeFiles(),report,'informe.docx');
assert.equal(transfer.name,'informe.docx');assert.match(transfer.mime,/wordprocessingml/);assert.ok(transfer.chunks.length>2);assert.equal(transfer.finished,true);assert.equal(transfer.aborted,undefined);
const restored=Buffer.concat(transfer.chunks.map(chunk=>Buffer.from(chunk,'base64')));
assert.equal(restored.length,500*1024);assert.ok(restored.every(byte=>byte===65));
stub('write-error');await assert.rejects(saveThroughBridge(nativeFiles(),report,'informe.docx'),/No se pudo escribir/);assert.equal(transfer.aborted,true);
stub('no-space');await assert.rejects(saveThroughBridge(nativeFiles(),report,'informe.docx'),/Libera espacio/);assert.equal(transfer.chunks.length,0);
stub('share-error');await assert.rejects(saveThroughBridge(nativeFiles(),report,'informe.docx'),/guardar o compartir/);
stub();const browserBlob=captured;await download(new Blob(['respaldo'],{type:'application/json'}),'respaldo.json');
assert.equal(captured,browserBlob);assert.equal(transfer.name,'respaldo.json');assert.equal(transfer.finished,true);
delete globalThis.AvgustFileBridge;assert.equal(nativeApp(),false);
await download(new Blob(['respaldo'],{type:'application/json'}),'respaldo.json');assert.notEqual(captured,browserBlob);
console.log('PASS: Android file bridge chunking, failure handling and browser download fallback');
