import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {mkdir} from 'node:fs/promises';
import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
function prepared(query,args=[]){return {bind(...values){return prepared(query,values)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}}}
const blobs=new Map();globalThis.testEnv={DB:{prepare:prepared,async batch(statements){sql.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}},FILES:{async put(k,v){blobs.set(k,v)},async get(k){if(!blobs.has(k))return null;const bytes=blobs.get(k);return {body:bytes,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}},async delete(k){blobs.delete(k)}}};
globalThis.testUser='owner';await mkdir('work/team-tests',{recursive:true});
await build({entryPoints:{team:'app/api/team/route.ts',audit:'app/api/audit/route.ts',commitments:'app/api/commitments/route.ts',dossier:'app/api/farms/[id]/dossier/route.ts',farmMetrics:'app/api/farms/[id]/metrics/route.ts',metricCompare:'app/api/farms/[id]/metrics/compare/route.ts',reports:'app/api/reports/route.ts',report:'app/api/reports/[id]/route.ts',requests:'app/api/requests/route.ts',visits:'app/api/visits/route.ts',visit:'app/api/visits/[id]/route.ts',photos:'app/api/photos/route.ts',photo:'app/api/photos/[id]/route.ts',backup:'app/api/backup/route.ts',backupFile:'lib/account-backup-file.ts'},bundle:true,platform:'node',format:'esm',packages:'external',outdir:'work/team-tests',plugins:[{name:'trusted-test-environment',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},args=>({contents:args.path==='env'?'export const env=globalThis.testEnv;':'export async function getChatGPTUser(){return globalThis.testUser?{userId:globalThis.testUser,displayName:globalThis.testUser,email:globalThis.testUser+"@test.invalid"}:null}'}));}}]});
const team=await import('../work/team-tests/team.js'),audit=await import('../work/team-tests/audit.js'),commitments=await import('../work/team-tests/commitments.js'),dossier=await import('../work/team-tests/dossier.js'),farmMetrics=await import('../work/team-tests/farmMetrics.js'),metricCompare=await import('../work/team-tests/metricCompare.js'),reports=await import('../work/team-tests/reports.js'),report=await import('../work/team-tests/report.js'),requests=await import('../work/team-tests/requests.js'),visits=await import('../work/team-tests/visits.js'),visit=await import('../work/team-tests/visit.js'),photos=await import('../work/team-tests/photos.js'),photo=await import('../work/team-tests/photo.js'),backup=await import('../work/team-tests/backup.js'),backupFile=await import('../work/team-tests/backupFile.js');
async function post(route,data,status=200){const r=await route.POST(new Request('https://test.invalid/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}));const x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
async function reportPost(data,status=200){return post(reports,data,status);}
async function reportList(visitId,status=200){const r=await reports.GET(new Request(`https://test.invalid/api/reports?visitId=${visitId}`)),x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
async function reportRead(id,status=200){const r=await report.GET(new Request(`https://test.invalid/api/reports/${id}`),{params:Promise.resolve({id})}),x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
async function readMetrics(query='',status=200){const r=await farmMetrics.GET(new Request(`https://test.invalid/api/farms/${farm.id}/metrics?${query}`),{params:Promise.resolve({id:farm.id})}),x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
async function compareMetrics(data,status=200){const r=await metricCompare.POST(new Request('https://test.invalid/api/farms/'+farm.id+'/metrics/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),{params:Promise.resolve({id:farm.id})}),x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
async function list(route){const r=await route.GET(new Request('https://test.invalid/api'));assert.equal(r.status,200);return r.json()}
const contacts=[{name:'Contacto',role:'Administración',phone:'3000000000',email:'contacto@finca.test',receiveReports:true}];
const farm=await post(team,{op:'create',name:'Finca Compartida',zone:'Sabana',contacts});const other=await post(team,{op:'create',name:'Otra Finca',zone:'',contacts});
assert.equal((await list(team)).farms[0].contacts[0].email,'contacto@finca.test');await post(team,{op:'contacts',farmId:farm.id,contacts:[{...contacts[0],name:'Gerencia',email:'gerencia@finca.test'}]});assert.equal((await list(team)).farms.find(f=>f.id===farm.id).contacts[0].name,'Gerencia');
async function auditList(status=200){const r=await audit.GET(new Request('https://test.invalid/api/audit?farmId='+farm.id));const x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
const initialAudit=await auditList();assert.ok(initialAudit.events.some(event=>event.event==='farm.created'));assert.ok(initialAudit.events.some(event=>event.event==='farm.contacts_updated'));assert.equal(JSON.stringify(initialAudit).includes('gerencia@finca.test'),false);
const editor=await post(team,{op:'invite',farmId:farm.id,role:'editor'}),viewer=await post(team,{op:'invite',farmId:farm.id,role:'viewer'}),revoked=await post(team,{op:'invite',farmId:farm.id,role:'viewer'});
globalThis.testUser='editor';await post(team,{op:'join',token:editor.token});await post(team,{op:'join',token:editor.token},400);await post(team,{op:'invite',farmId:farm.id,role:'manager'},403);await auditList(403);
globalThis.testUser='viewer';await post(team,{op:'join',token:viewer.token});assert.equal((await list(team)).farms.length,1);await auditList(403);
const service={id:'',farmId:farm.id,revision:0,kind:'assurance',reason:'Revisar equipos',date:'2026-09-10',rtc:'owner',assignee:'editor',status:'scheduled'};
await post(requests,service,403);globalThis.testUser='editor';await post(requests,service,403);globalThis.testUser='owner';const request=await post(requests,service);await post(requests,{...request,assignee:'stranger'},403);await post(requests,{...request,farmId:other.id,rtc:'',assignee:'',status:'requested'},403);
const v={id:'',revision:0,farm:'Finca personal',date:'2026-09-08',city:'',zone:'',technician:'Contacto',responsible:'Owner',rtc:'',chapters:[3],answers:{},notes:{},recommendations:{},measurements:{},delivery:'',followup:'',conclusion:'',photos:[],reviewed:false};
const personal=await post(visits,v);const photoResponse=await photos.POST(new Request('https://test.invalid/api/photos',{method:'POST',body:new Uint8Array([137,80,78,71,1,2,3])}));const uploaded=await photoResponse.json();
const shared=await post(visits,{...personal,farmId:farm.id,requestId:request.id,photos:[{id:uploaded.id,chapter:3,caption:'Equipo'}]});assert.equal(shared.farm,'Finca Compartida');
const reviewedShared=await post(visits,{...shared,reviewed:true,answers:{'3.1':{value:'SI',observation:'',recommendation:''},'3.2':{value:'SI',observation:'',recommendation:''},'3.3':{value:'NO',observation:'Equipo sin cierre',recommendation:'Asegurar el cierre'},'3.4':{value:'NA',observation:'',recommendation:''}},actions:{'3.3':{owner:'Técnica',due:'2026-10-01',status:'pending',closure:'',beforePhotoId:'',photoId:''}}});
async function readDossier(url=`https://test.invalid/api/farms/${farm.id}/dossier?limit=2`,status=200){const r=await dossier.GET(new Request(url),{params:Promise.resolve({id:farm.id})});const x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
const firstDossier=await readDossier();assert.equal(firstDossier.summary.visits,1);assert.equal(firstDossier.summary.reports,1);assert.equal(firstDossier.summary.openRequests,1);assert.equal(firstDossier.summary.pendingFollowups,1);assert.equal(firstDossier.summary.photos,1);assert.equal(firstDossier.events.length,2);assert.ok(firstDossier.nextCursor);const secondDossier=await readDossier(`https://test.invalid/api/farms/${farm.id}/dossier?limit=2&cursor=${encodeURIComponent(firstDossier.nextCursor)}`);assert.ok(secondDossier.events.length>0);const reportsDossier=await readDossier(`https://test.invalid/api/farms/${farm.id}/dossier?types=report`);assert.equal(reportsDossier.events.length,1);assert.equal(reportsDossier.events[0].visitId,reviewedShared.id);
const reportDraft=await reportPost({op:'create',visitId:reviewedShared.id});assert.equal(reportDraft.versionNumber,1);assert.equal(reportDraft.status,'draft');assert.equal((await reportList(reviewedShared.id)).role,'manager');
const submitted=await reportPost({op:'submit',id:reportDraft.id,revision:reportDraft.revision});assert.equal(submitted.status,'in_review');const frozen=await reportRead(reportDraft.id);assert.equal(frozen.snapshot.content.conclusion,'');assert.equal(JSON.stringify(frozen.snapshot).includes('137,80,78'),false);assert.equal(frozen.snapshot.photos,undefined);assert.equal(frozen.snapshot.content.photos[0].id,uploaded.id);
globalThis.testUser='editor';await reportPost({op:'approve',id:submitted.id,revision:submitted.revision},403);const changedAfterSubmit=await post(visits,{...reviewedShared,conclusion:'Actualizado después del envío'});globalThis.testUser='owner';await reportPost({op:'approve',id:submitted.id,revision:submitted.revision},409);const returned=await reportPost({op:'return',id:submitted.id,revision:submitted.revision});assert.equal(returned.status,'draft');globalThis.testUser='editor';const resubmitted=await reportPost({op:'submit',id:returned.id,revision:returned.revision});globalThis.testUser='owner';const approved=await reportPost({op:'approve',id:resubmitted.id,revision:resubmitted.revision});const published=await reportPost({op:'publish',id:approved.id,revision:approved.revision});assert.equal(published.status,'published');const publishedSnapshot=await reportRead(published.id);assert.equal(publishedSnapshot.snapshot.content.conclusion,'Actualizado después del envío');const versionTwo=await reportPost({op:'new_version',visitId:reviewedShared.id});assert.equal(versionTwo.versionNumber,2);assert.equal((await reportRead(published.id)).status,'published');const formalDossier=await readDossier(`https://test.invalid/api/farms/${farm.id}/dossier?types=report`);assert.equal(formalDossier.events.length,1);assert.equal(formalDossier.events[0].reportVersionId,published.id);
const metricVisit=await post(visits,{...changedAfterSubmit,id:'',revision:0,requestId:undefined,date:'2026-10-10',photos:[],actions:{},answers:{'3.1':{value:'SI',observation:'',recommendation:''},'3.2':{value:'SI',observation:'',recommendation:''},'3.3':{value:'SI',observation:'',recommendation:''},'3.4':{value:'NA',observation:'',recommendation:''}},measurements:{ph:'6.10',pressure:'32',volume:'2',equipment:'Jacto XP'}});
const originalMetric=await post(visits,{...metricVisit,id:'',revision:0,date:'2026-09-10',measurements:{ph:'6.40',pressure:'30',volume:'0',equipment:'Jacto XP'},answers:{'3.1':{value:'SI',observation:'',recommendation:''},'3.2':{value:'SI',observation:'',recommendation:''},'3.3':{value:'NO',observation:'Equipo sin cierre',recommendation:'Asegurar el cierre'},'3.4':{value:'NA',observation:'',recommendation:''}}});
const latestMetricPage=await readMetrics('metric=ph&limit=1');assert.equal(latestMetricPage.points.length,1);assert.equal(latestMetricPage.points[0].originalValue,'6.10');assert.ok(latestMetricPage.nextCursor);const priorMetricPage=await readMetrics(`metric=ph&limit=1&cursor=${encodeURIComponent(latestMetricPage.nextCursor)}`);assert.equal(priorMetricPage.points[0].originalValue,'6.40');const rangedMetricPage=await readMetrics('metric=ph&from=2026-10-01&to=2026-10-31');assert.equal(rangedMetricPage.points.length,1);await readMetrics('metric=equipment',400);
const compared=await compareMetrics({visitAId:originalMetric.id,visitBId:metricVisit.id});assert.equal(compared.comparisons.find(item=>item.metric.id==='ph').comparison.delta,-0.3);assert.equal(compared.comparisons.find(item=>item.metric.id==='compliance').comparison.differenceLabel,'+33 puntos porcentuales');assert.equal(compared.comparisons.find(item=>item.metric.id==='volume').comparison.relativeChange,null);assert.equal(compared.comparisons.find(item=>item.metric.id==='equipment').comparison.change,'same');const otherMetric=await post(visits,{...metricVisit,id:'',revision:0,farmId:other.id,farm:'Otra Finca',date:'2026-10-11'});await compareMetrics({visitAId:otherMetric.id,visitBId:metricVisit.id},404);
for(let index=0;index<180;index++){const id=`00000000-0000-4000-8000-${String(index).padStart(12,'0')}`,month=String(index%12+1).padStart(2,'0'),day=String(index%27+1).padStart(2,'0'),date=`${2020+Math.floor(index/12)}-${month}-${day}`,payload={...metricVisit,id,revision:1,date,measurements:{ph:String(5.5+(index%15)/10)},photos:[],actions:{}};sql.prepare('INSERT INTO visits (id,owner,farm,farm_id,date,payload,revision,updated) VALUES (?,?,?,?,?,?,?,?)').run(id,'owner','Finca Compartida',farm.id,date,JSON.stringify(payload),1,`${date}T12:00:00.000Z`);}const benchmarkStarted=performance.now(),benchmark=await readMetrics('metric=ph&limit=30'),benchmarkMs=performance.now()-benchmarkStarted;assert.equal(benchmark.points.length,30);assert.ok(benchmark.nextCursor);assert.ok(benchmarkMs<2000,`Consulta histórica demasiado lenta: ${benchmarkMs} ms`);
const readPhoto=()=>photo.GET(new Request('https://test.invalid/api/photos/'+uploaded.id),{params:Promise.resolve({id:uploaded.id})});
const readVisit=()=>visit.GET(new Request('https://test.invalid/api/visits/'+reviewedShared.id),{params:Promise.resolve({id:reviewedShared.id})});
globalThis.testUser='viewer';const visibleVisits=await list(visits);assert.ok(visibleVisits.some(item=>item.id===reviewedShared.id));assert.equal(visibleVisits.find(item=>item.id===reviewedShared.id).canEdit,false);assert.equal((await readVisit()).status,200);assert.equal((await readPhoto()).status,200);assert.equal((await reportList(reviewedShared.id)).versions.length,2);await readMetrics('metric=ph&limit=1');await compareMetrics({visitAId:originalMetric.id,visitBId:metricVisit.id});await reportPost({op:'submit',id:versionTwo.id,revision:versionTwo.revision},403);await post(visits,reviewedShared,403);await readDossier(undefined,200);
const deniedUpload=await photos.POST(new Request('https://test.invalid/api/photos?farmId='+farm.id,{method:'POST',body:new Uint8Array([137,80,78,71])}));assert.equal(deniedUpload.status,403);
globalThis.testUser='editor';const edited=await post(visits,{...changedAfterSubmit,conclusion:'Actualizado por participante'});await post(visits,changedAfterSubmit,409);await post(visits,{...edited,farmId:other.id},400);
async function readCommitments(query='',status=200){const r=await commitments.GET(new Request(`https://test.invalid/api/commitments?farmId=${farm.id}${query}`));const x=await r.json();assert.equal(r.status,status,JSON.stringify(x));return x;}
await post(visits,{...edited,id:'',revision:0,date:'2026-10-02',actions:{},photos:[]});const firstCommitmentPage=await readCommitments('&limit=1');assert.equal(firstCommitmentPage.items.length,1);assert.ok(firstCommitmentPage.nextCursor);const secondCommitmentPage=await readCommitments(`&limit=1&cursor=${encodeURIComponent(firstCommitmentPage.nextCursor)}`);assert.ok(secondCommitmentPage.items.length>0);const pendingCommitment=firstCommitmentPage.items.find(item=>item.action.status==='pending')||secondCommitmentPage.items.find(item=>item.action.status==='pending');assert.ok(pendingCommitment);
const completedCommitment=await post(commitments,{visitId:pendingCommitment.visitId,criterionId:pendingCommitment.criterionId,revision:pendingCommitment.revision,action:{owner:'Técnica',due:'2026-10-01',status:'closed',closure:'Cierre verificado sin fotografía obligatoria'}});assert.equal(completedCommitment.action.status,'closed');assert.equal(completedCommitment.action.completedBy,'editor');assert.ok(completedCommitment.action.completedAt);const completedPage=await readCommitments('&bucket=completed');assert.ok(completedPage.items.some(item=>item.id===pendingCommitment.id));
const reopenedCommitment=await post(commitments,{visitId:pendingCommitment.visitId,criterionId:pendingCommitment.criterionId,revision:completedCommitment.revision,action:{owner:'Técnica',due:'2026-10-03',status:'progress',closure:'Se requiere una verificación adicional'}});assert.equal(reopenedCommitment.action.status,'progress');assert.ok(reopenedCommitment.action.reopenedAt);const cancelledCommitment=await post(commitments,{visitId:pendingCommitment.visitId,criterionId:pendingCommitment.criterionId,revision:reopenedCommitment.revision,action:{owner:'Técnica',due:'2026-10-03',status:'cancelled',closure:'Compromiso cancelado'}});assert.equal(cancelledCommitment.action.status,'cancelled');const cancelledPage=await readCommitments('&status=cancelled');assert.ok(cancelledPage.items.some(item=>item.id===pendingCommitment.id));await readCommitments('&bucket=overdue');globalThis.testUser='viewer';await readCommitments();await post(commitments,{visitId:pendingCommitment.visitId,criterionId:pendingCommitment.criterionId,revision:cancelledCommitment.revision,action:{owner:'Técnica',due:'2026-10-03',status:'progress',closure:'Intento no autorizado'}},403);globalThis.testUser='editor';
globalThis.testUser='stranger';assert.equal((await list(visits)).length,0);assert.equal((await list(requests)).length,0);assert.equal((await readVisit()).status,404);assert.equal((await readPhoto()).status,404);await readDossier(undefined,403);await readMetrics('metric=ph',403);await compareMetrics({visitAId:originalMetric.id,visitBId:metricVisit.id},403);await post(visits,edited,403);await readCommitments('',403);
globalThis.testUser='owner';await post(team,{op:'revokeInvite',farmId:farm.id,token:revoked.token});await post(team,{op:'member',farmId:farm.id,userId:'viewer',role:'editor'});await post(team,{op:'member',farmId:farm.id,userId:'editor',role:'remove'});await post(team,{op:'member',farmId:farm.id,userId:'owner',role:'remove'},400);
const finalAudit=await auditList();assert.ok(finalAudit.events.some(event=>event.event==='team.invitation_created'));assert.ok(finalAudit.events.some(event=>event.event==='team.invitation_revoked'));assert.ok(finalAudit.events.some(event=>event.event==='team.member_joined'&&event.subjectId==='editor'));assert.ok(finalAudit.events.some(event=>event.event==='team.member_role_changed'&&event.subjectId==='viewer'));assert.ok(finalAudit.events.some(event=>event.event==='team.member_removed'&&event.subjectId==='editor'));assert.ok(finalAudit.events.some(event=>event.event==='report_draft_created'));assert.ok(finalAudit.events.some(event=>event.event==='report_submitted'));assert.ok(finalAudit.events.some(event=>event.event==='report_returned'));assert.ok(finalAudit.events.some(event=>event.event==='report_approved'));assert.ok(finalAudit.events.some(event=>event.event==='report_published'));assert.ok(finalAudit.events.some(event=>event.event==='report_version_created'));assert.ok(finalAudit.events.some(event=>event.event==='commitment.completed'));assert.ok(finalAudit.events.some(event=>event.event==='commitment.reopened'));assert.ok(finalAudit.events.some(event=>event.event==='commitment.cancelled'));assert.equal(JSON.stringify(finalAudit).includes(editor.token),false);assert.equal(JSON.stringify(finalAudit).includes(revoked.token),false);
globalThis.testUser='editor';assert.equal((await list(visits)).length,0);assert.equal((await readPhoto()).status,404);await post(visits,edited,403);
globalThis.testUser='owner';
const backupResponse=await backup.GET(new Request('https://test.invalid/api/backup')),accountBackup=await backupResponse.json();
assert.equal(backupResponse.status,200);assert.equal(accountBackup.format,'avgust-care-360-account-backup');assert.equal(accountBackup.version,1);
assert.ok(accountBackup.visits.some(item=>item.id===metricVisit.id));assert.ok(accountBackup.reports.some(item=>item.visit_id===reviewedShared.id));assert.ok(accountBackup.photos.some(item=>item.id===uploaded.id));assert.ok(accountBackup.farms.some(item=>item.id===farm.id));
const wasmPath=join(process.cwd(),'node_modules','sql.js','dist','sql-wasm.wasm'),care360Bytes=await backupFile.createCare360Backup(accountBackup,()=>wasmPath);
assert.equal(new TextDecoder().decode(care360Bytes.slice(0,16)),'SQLite format 3\u0000');
const parsedCare360=await backupFile.readCare360Backup(care360Bytes,'owner',()=>wasmPath);
assert.equal(parsedCare360.bundle.farms.length,accountBackup.farms.length);assert.equal(parsedCare360.bundle.visits.length,accountBackup.visits.length);assert.equal(parsedCare360.bundle.photos.length,accountBackup.photos.length);
if(accountBackup.requests.length){const SQL=await (await import('sql.js')).default({locateFile:()=>wasmPath}),database=new SQL.Database(care360Bytes),request=accountBackup.requests[0],farmId=request.farmId;database.run('INSERT INTO farm_members (farm_id,user_id,name,role) VALUES (?,?,?,?)',[farmId,'local-member','Participante local','editor']);database.run('UPDATE service_requests SET payload=? WHERE id=?',[JSON.stringify({...request,rtc:'local-member',assignee:'local-member',status:'scheduled'}),request.id]);const assignedBytes=database.export();database.close();assert.equal((await backupFile.readCare360Backup(assignedBytes,'owner',()=>wasmPath)).unassignedRequests,1);}
let fixtureSummary='';
if(process.env.CARE360_FIXTURE_PATH){const fixture=await backupFile.readCare360Backup(new Uint8Array(readFileSync(process.env.CARE360_FIXTURE_PATH)),'owner',()=>wasmPath);assert.ok(fixture.bundle.farms.length);assert.ok(fixture.bundle.visits.length);assert.ok(fixture.bundle.photos.length);const mergedFixture=await importBackup(fixture.bundle);assert.equal(mergedFixture.farmsCreated,fixture.bundle.farms.length);assert.equal(mergedFixture.visitsImported,fixture.bundle.visits.length);assert.equal(mergedFixture.photosImported,fixture.bundle.photos.length);fixtureSummary=`; actual .care360 fixture imported (${fixture.bundle.farms.length} farms, ${fixture.bundle.visits.length} visits, ${fixture.bundle.photos.length} photos)`;}
async function importBackup(bundle,status=200){const response=await backup.POST(new Request('https://test.invalid/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(bundle)}));const result=await response.json();assert.equal(response.status,status,JSON.stringify(result));return result;}
globalThis.testUser='intruder';await importBackup(accountBackup,403);globalThis.testUser='owner';
const keptVisit=sql.prepare('SELECT payload FROM visits WHERE id=?').get(reviewedShared.id),keptPayload=JSON.parse(keptVisit.payload);keptPayload.conclusion='Mantener versión actual';sql.prepare('UPDATE visits SET payload=? WHERE id=?').run(JSON.stringify(keptPayload),reviewedShared.id);
sql.prepare('DELETE FROM visits WHERE id=?').run(metricVisit.id);
sql.prepare('DELETE FROM report_versions WHERE visit_id=?').run(reviewedShared.id);
sql.prepare("UPDATE farm_contacts SET name='Contacto actualizado' WHERE farm_id=?").run(farm.id);
const savedRequest=sql.prepare('SELECT payload FROM service_requests WHERE id=?').get(request.id),changedRequest=JSON.parse(savedRequest.payload);changedRequest.status='done';sql.prepare('UPDATE service_requests SET payload=? WHERE id=?').run(JSON.stringify(changedRequest),request.id);
const photoKey=sql.prepare('SELECT key FROM photos WHERE id=?').get(uploaded.id).key;sql.prepare('DELETE FROM photos WHERE id=?').run(uploaded.id);blobs.delete(photoKey);
const restored=await importBackup(accountBackup);
assert.equal(restored.visitsImported,1);assert.equal(restored.photosImported,1);assert.equal(restored.reportsImported,2);
assert.equal(JSON.parse(sql.prepare('SELECT payload FROM visits WHERE id=?').get(reviewedShared.id).payload).conclusion,'Mantener versión actual');
assert.ok(sql.prepare('SELECT id FROM visits WHERE id=?').get(metricVisit.id));assert.ok(sql.prepare('SELECT id FROM photos WHERE id=?').get(uploaded.id));assert.equal(blobs.has(sql.prepare('SELECT key FROM photos WHERE id=?').get(uploaded.id).key),true);
assert.equal(sql.prepare('SELECT name FROM farm_contacts WHERE farm_id=?').get(farm.id).name,'Contacto actualizado');assert.equal(JSON.parse(sql.prepare('SELECT payload FROM service_requests WHERE id=?').get(request.id).payload).status,'done');
const recoveredPhotoKey=sql.prepare('SELECT key FROM photos WHERE id=?').get(uploaded.id).key;blobs.delete(recoveredPhotoKey);
assert.equal((await importBackup(accountBackup)).photosImported,1);assert.equal(blobs.has(recoveredPhotoKey),true);
assert.equal((await importBackup(accountBackup)).visitsImported,0);
globalThis.testUser=null;assert.equal((await team.GET(new Request('https://test.invalid/api'))).status,401);
console.log(`PASS: migrations, formal report lifecycle, immutable snapshots, metric history and comparison (${Math.round(benchmarkMs)} ms / 180 visits), audit trail, paginated farm dossier, scoped roles, private visits, shared photos, viewer read-only, revocation, stale writes, account backup authorization, photo/report recovery and non-overwriting idempotent merge${fixtureSummary}`);
sql.close();
