'use client';
import {useMemo,useState} from 'react';
import {FileDown,FileSpreadsheet,Printer} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {catalog,metricStatusLabels,metricTrendLabels,type MetricStatus,type Visit} from '@/lib/model';
import {compareFarmBenchmarks,consolidatedMetricAnalysis} from '@/lib/metric-analysis';
import {exportConsolidatedMatrixExcel} from '@/lib/export-matrix-excel';
import {exportConsolidatedMatrixCsv} from '@/lib/export-matrix-csv';
import {exportConsolidatedWord} from '@/lib/export-consolidated-word';
import ImportMatrix from './import-matrix';
import {ConsolidatedChapterDetails} from './metric-chapter-details';

function Status({value}:{value:MetricStatus}){return <span className={'metric-status '+value}>{metricStatusLabels[value]}</span>;}
const monthLabel=(period:string)=>new Intl.DateTimeFormat('es-CO',{month:'short',year:'numeric'}).format(new Date(`${period}-01T12:00:00`));

export default function ConsolidatedMetrics({visits,loading,onImport}:{visits:Visit[];loading:boolean;onImport:(visits:Visit[])=>Promise<void>}){
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [month,setMonth]=useState('');
 const scoped=useMemo(()=>visits.filter(v=>(!from||v.date>=`${from}-01-01`)&&(!to||v.date<=`${to}-12-31`)&&(!month||v.date.startsWith(month))),[visits,from,to,month]);
 const data=useMemo(()=>consolidatedMetricAnalysis(scoped),[scoped]);
 const benchmark=useMemo(()=>compareFarmBenchmarks(scoped),[scoped]);
 const chart=data.timeline.map(row=>({...row,label:monthLabel(row.period)}));
 const chapterChart=data.chapters.map(row=>({chapter:`${row.id}`,hallazgos:row.findings}));
 return <section className="metrics-panel consolidated-panel" aria-labelledby="consolidated-title"><div className="metrics-print-brand"><img src="/avgust-logo.svg" alt="Avgust Crop Protection"/><div><strong>AVGUST CARE 360</strong><span>Consolidado de aseguramientos</span></div></div><div className="page-heading"><div><div className="eyebrow">MATRIZ TÉCNICA</div><h2 id="consolidated-title">Consolidado de aseguramientos</h2><p>Analiza todas las fincas para identificar los capítulos y criterios que más generan inconvenientes.</p></div>{data.records.length>0&&<div className="metrics-actions no-print"><button className="secondary" onClick={()=>void exportConsolidatedWord(data,month||`${from||'Inicio'} a ${to||'hoy'}`)}><FileSpreadsheet size={17}/>Informe mensual Word</button><button className="secondary" onClick={()=>void exportConsolidatedMatrixExcel(data)}><FileSpreadsheet size={17}/>Descargar matriz Excel</button><button className="secondary" onClick={()=>void exportConsolidatedMatrixCsv(data)}><FileDown size={17}/>Descargar CSV</button><button className="primary" onClick={()=>window.print()}><Printer size={17}/>Guardar PDF</button></div>}</div>
 <div className="metrics-filters compact no-print"><label>Mes del informe<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>Desde<input type="number" min="2020" max="2100" placeholder="2022" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="number" min="2020" max="2100" placeholder="2026" value={to} onChange={e=>setTo(e.target.value)}/></label></div><ImportMatrix onImport={onImport}/>
 {loading?<p role="status">Cargando consolidado…</p>:!data.records.length?<div className="notice">No hay aseguramientos revisados con criterios aplicables en el periodo seleccionado.</div>:<><div className="metric-summary"><div><span>Indicador consolidado</span><b>{data.score}%</b><Status value={data.status}/></div><div><span>Comportamiento global</span><b className={'trend '+data.trend}>{metricTrendLabels[data.trend]}</b><small>Comparación del primer y último periodo</small></div><div><span>Fincas evaluadas</span><b>{data.farms}</b><small>{data.records.length} aseguramientos revisados</small></div><div><span>Inconvenientes</span><b>{data.findings}</b><small>de {data.applicable} criterios aplicables</small></div></div>
 <section className="farm-benchmark section-gap" aria-labelledby="farm-benchmark-title"><div className="eyebrow">COMPARACIÓN ENTRE FINCAS</div><h3 id="farm-benchmark-title">Resultados con el mismo alcance</h3><p className="muted">Se compara el informe revisado más reciente de cada finca dentro del periodo seleccionado. Solo se agrupan fincas que evaluaron los mismos capítulos; el porcentaje usa el indicador oficial 1.5.35.</p>{benchmark.groups.length?benchmark.groups.map(group=>{const scope=group.chapterIds.map(id=>catalog.find(chapter=>chapter.id===id)?.title||`Capítulo ${id}`).join(' · ');return <section className="farm-benchmark-group" key={group.chapterIds.join('-')}><h4>{scope}</h4><div className="table-scroll"><table className="followup-table metric-table"><thead><tr><th>Posición</th><th>Finca</th><th>Último informe</th><th>Indicador oficial</th><th>Hallazgos</th><th>Criterios aplicables</th></tr></thead><tbody>{group.records.map(record=><tr key={record.farm}><td>{record.tied?`Empate · ${record.rank}`:record.rank}</td><td><strong>{record.farm}</strong></td><td>{record.date}</td><td><strong>{record.score}%</strong></td><td>{record.findings}</td><td>{record.applicable}</td></tr>)}</tbody></table></div></section>;}):<p className="metric-clear">Aún no hay dos fincas con informes revisados de alcance equivalente en este periodo; no se presenta una clasificación incomparable.</p>}{benchmark.singleScopes.length>0&&<details className="benchmark-note"><summary>{benchmark.singleScopes.length} finca{benchmark.singleScopes.length===1?'':'s'} con un alcance distinto o sin pares comparables</summary><ul>{benchmark.singleScopes.map(item=><li key={item.farm}>{item.farm} · {item.date} · {item.chapterIds.length?item.chapterIds.map(id=>`Cap. ${id}`).join(', '):'sin capítulos seleccionados'}</li>)}</ul></details>}{benchmark.ambiguousFarms.length>0&&<p className="benchmark-note" role="note">No se clasifican {benchmark.ambiguousFarms.length} finca{benchmark.ambiguousFarms.length===1?'':'s'} porque tienen más de un informe revisado en su fecha más reciente: {benchmark.ambiguousFarms.join(', ')}. Ajusta el periodo para consultar una única medición por finca.</p>}</section>
 <div className="metric-grid"><section className="metric-chart"><div><h3>Indicador consolidado por periodo</h3><p>Promedio ponderado de los aseguramientos revisados.</p></div><div className="chart-scroll"><div style={{minWidth:Math.max(620,chart.length*96)}}><ResponsiveContainer width="100%" height={265}><LineChart data={chart} margin={{top:15,right:16,left:-15,bottom:4}}><XAxis dataKey="label" tickLine={false} axisLine={false} minTickGap={24}/><YAxis domain={[0,100]} tickLine={false} axisLine={false} tickFormatter={v=>`${v}%`}/><Tooltip formatter={value=>[`${value}%`,'Indicador']}/><Line type="monotone" dataKey="score" name="Indicador" stroke="#007fa3" strokeWidth={3} dot={{r:5,fill:'#78be20'}} activeDot={{r:7}} isAnimationActive animationDuration={900} animationEasing="ease-out"/></LineChart></ResponsiveContainer></div></div></section><section className="metric-chart"><div><h3>Hallazgos por capítulo</h3><p>Las barras más altas señalan dónde concentrar acciones.</p></div><ResponsiveContainer width="100%" height={265}><BarChart data={chapterChart} margin={{top:15,right:8,left:-10,bottom:4}}><CartesianGrid vertical={false} stroke="#e3ebeb"/><XAxis dataKey="chapter" tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip formatter={value=>[value,'Hallazgos']} labelFormatter={label=>`Capítulo ${label}`}/><Bar dataKey="hallazgos" name="Hallazgos" fill="#f2a900" radius={[5,5,0,0]} isAnimationActive animationDuration={850} animationEasing="ease-out"/></BarChart></ResponsiveContainer></section></div>
 <section className="section-gap"><div className="eyebrow">PRIORIZACIÓN</div><h3>Ítems con más inconvenientes</h3><p className="muted">Ordenados por número de respuestas “No”. La matriz Excel contiene el detalle completo por finca e informe.</p><div className="table-scroll"><table className="followup-table metric-table"><thead><tr><th>Capítulo</th><th>Ítem</th><th>Inconveniente</th><th>Hallazgos</th><th>Frecuencia</th><th>Fincas</th></tr></thead><tbody>{data.items.filter(item=>item.findings>0).slice(0,12).map(item=><tr key={item.id}><td>{item.chapter}. {item.chapterTitle}</td><td><strong>{item.id}</strong></td><td>{item.text}</td><td><strong>{item.findings}</strong></td><td><span className={item.rate>=50?'trend declined':'trend stable'}>{item.rate}%</span></td><td>{item.farms}</td></tr>)}</tbody></table></div>{!data.items.some(item=>item.findings>0)&&<p className="metric-clear">No hay respuestas “No” en los aseguramientos del periodo.</p>}</section>
 <section className="section-gap"><h3>Estado consolidado por capítulo</h3><ConsolidatedChapterDetails chapters={data.chapters} items={data.items}/></section></>}
 </section>;
}
