'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,CalendarCheck,CalendarDays,Camera,ClipboardCheck,Clock3,FileText,FolderSearch,MapPin,Search,Users} from 'lucide-react';
import {metricStatusLabels,type MetricStatus} from '@/lib/model';
import type {DossierEvent,DossierKind,FarmDossier} from '@/lib/farm-dossier';
import type {Farm} from '@/lib/team';

const filters:{value:'all'|DossierKind;label:string}[]=[{value:'all',label:'Todos'},{value:'visit',label:'Visitas'},{value:'request',label:'Solicitudes'},{value:'report',label:'Informes'},{value:'photo',label:'Fotos'},{value:'followup',label:'Seguimientos'}];
const kindLabel:Record<DossierKind,string>={visit:'Visita técnica',request:'Solicitud',report:'Informe',photo:'Fotografías',followup:'Seguimiento'};

function Status({value}:{value:MetricStatus}){return <span className={'metric-status '+value}>{metricStatusLabels[value]}</span>;}
function EventIcon({kind}:{kind:DossierKind}){const Icon=kind==='visit'?ClipboardCheck:kind==='request'?CalendarDays:kind==='report'?FileText:kind==='photo'?Camera:CalendarCheck;return <Icon size={19}/>;}
function dateText(value:string){if(!value)return 'Fecha por definir';const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric'}).format(date);}
function queryParameters(kind:'all'|DossierKind,range:{from:string;to:string},cursor?:string){const values=new URLSearchParams({limit:'20'});if(kind!=='all')values.set('types',kind);if(range.from)values.set('from',range.from);if(range.to)values.set('to',range.to);if(cursor)values.set('cursor',cursor);return values;}

export default function FarmDossier({farms,onOpenVisit,onOpenRequest,onNew}:{farms:Farm[];onOpenVisit:(id:string)=>void;onOpenRequest:(id:string)=>void;onNew:(farm:Farm)=>void}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[kind,setKind]=useState<'all'|DossierKind>('all');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[appliedRange,setAppliedRange]=useState({from:'',to:''});
 const [dossier,setDossier]=useState<FarmDossier|null>(null),[loading,setLoading]=useState(false),[moreLoading,setMoreLoading]=useState(false),[error,setError]=useState('');
 const requestVersion=useRef(0);
 const matches=useMemo(()=>farms.filter(f=>!query||f.name.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es'))).slice(0,8),[farms,query]);
 const farm=farms.find(item=>item.id===selected);
 useEffect(()=>{let current=true;if(!selected)return;const version=++requestVersion.current;const timer=window.setTimeout(()=>{setLoading(true);setError('');void fetch(`/api/farms/${selected}/dossier?${queryParameters(kind,appliedRange).toString()}`).then(async response=>{const body=await response.json() as FarmDossier&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo consultar el expediente.');return body;}).then(result=>{if(current&&version===requestVersion.current)setDossier(result);}).catch(reason=>{if(current)setError((reason as Error).message);}).finally(()=>{if(current)setLoading(false);});},0);return()=>{current=false;window.clearTimeout(timer);};},[selected,kind,appliedRange]);
 async function loadMore(){if(!dossier?.nextCursor||!selected)return;setMoreLoading(true);setError('');try{const response=await fetch(`/api/farms/${selected}/dossier?${queryParameters(kind,appliedRange,dossier.nextCursor).toString()}`);const body=await response.json() as FarmDossier&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo cargar más actividad.');setDossier(previous=>previous?{...body,events:[...previous.events,...body.events]}:body);}catch(reason){setError((reason as Error).message);}finally{setMoreLoading(false);}}
 function selectFarm(next:Farm){setDossier(null);setSelected(next.id);setQuery(next.name);setAppliedRange({from:'',to:''});setFrom('');setTo('');}
 function open(event:DossierEvent){if(event.visitId)onOpenVisit(event.visitId);else if(event.requestId)onOpenRequest(event.requestId);}
 return <section className="farm-dossier" aria-labelledby="dossier-title"><div className="dossier-hero"><div><div className="eyebrow">EXPEDIENTE TÉCNICO</div><h2 id="dossier-title">Consulta de finca</h2><p>Una historia cronológica de solicitudes, visitas, informes, fotografías y seguimientos, sin duplicar los registros originales.</p></div><div className="dossier-search"><label htmlFor="dossier-search">Buscar finca</label><div><Search size={20}/><input id="dossier-search" value={query} placeholder="Escribe el nombre de una finca" onChange={event=>{setQuery(event.target.value);if(selected&&event.target.value!==farm?.name)setSelected('');}}/></div>{query&&!selected&&<div className="dossier-matches">{matches.length?matches.map(item=><button key={item.id} onClick={()=>selectFarm(item)}><span>{item.name}<small>{item.zone||'Zona sin registrar'}</small></span><ArrowRight size={16}/></button>):<p>No hay fincas registradas que coincidan.</p>}</div>}</div></div>
 {!selected?<div className="dossier-empty"><FolderSearch size={30}/><strong>Elige una finca para abrir su expediente</strong><p>Solo aparecen fincas registradas a las que tienes acceso. Los informes históricos sin finca asignada permanecen en Visitas e informes.</p>{!query&&farms.slice(0,6).map(item=><button className="secondary" key={item.id} onClick={()=>selectFarm(item)}>{item.name}</button>)}</div>:loading&&!dossier?<output className="dossier-empty"><Clock3 size={30}/><strong>Preparando el expediente…</strong><p>Se carga una página de actividad, no todo el historial de la finca.</p></output>:farm&&dossier?<><header className="dossier-heading"><div><div className="eyebrow">FINCA</div><h3>{dossier.farm.name}</h3><p><MapPin size={16}/>{dossier.farm.zone||'Zona sin registrar'}</p></div><div className="dossier-heading-actions"><button className="primary" onClick={()=>onNew(farm)}><FileText size={17}/>Nuevo informe</button><span><Users size={16}/>{farm.members.length} participante{farm.members.length===1?'':'s'}</span></div></header>
 <div className="dossier-stats"><article><span>Última visita revisada</span><b>{dossier.summary.latestVisit?dateText(dossier.summary.latestVisit.date):'—'}</b><small>{dossier.summary.latestVisit?.responsible||'Sin informe revisado'}</small></article><article><span>Visitas registradas</span><b>{dossier.summary.visits}</b><small>{dossier.summary.photos} fotografías asociadas</small></article><article><span>Solicitudes abiertas</span><b>{dossier.summary.openRequests}</b><small>Solicitadas o programadas</small></article><article><span>Informes revisados</span><b>{dossier.summary.reports}</b><small>Derivados de visitas revisadas</small></article><article><span>Pendientes de seguimiento</span><b>{dossier.summary.pendingFollowups}</b><small>Compromisos aceptados o en proceso</small></article></div>
 <section className="dossier-current"><div><div className="eyebrow">SITUACIÓN ACTUAL</div><h3>{dossier.summary.latestVisit?.score===null||!dossier.summary.latestVisit?'Sin medición revisada':`${dossier.summary.latestVisit.score}%`}</h3><p>{dossier.summary.latestVisit?<Status value={dossier.summary.latestVisit.status}/>:<>Registra y revisa un aseguramiento para calcular el indicador.</>}</p></div><p>{dossier.summary.latestVisit?`Indicador de la última visita revisada del ${dateText(dossier.summary.latestVisit.date)}.`:'El expediente conserva la actividad aunque todavía no exista una medición aplicable.'}</p></section>
 <section className="dossier-activity"><div className="dossier-activity-heading"><div><div className="eyebrow">ACTIVIDAD RECIENTE</div><h3>Línea de tiempo</h3><p>Abre cada elemento para ir a su visita o solicitud original.</p></div><div className="dossier-range"><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="secondary" onClick={()=>setAppliedRange({from,to})}>Aplicar</button></div></div><div className="dossier-filters" aria-label="Filtrar actividad">{filters.map(filter=><button key={filter.value} className={kind===filter.value?'active':''} onClick={()=>setKind(filter.value)}>{filter.label}</button>)}</div>{error&&<p role="alert" className="notice error">{error}</p>}{dossier.events.length?<ol className="dossier-timeline">{dossier.events.map(event=><li key={event.id}><time>{dateText(event.occurredOn)}</time><div className={'dossier-event '+event.kind}><div className="dossier-event-icon"><EventIcon kind={event.kind}/></div><div><span className="dossier-kind">{kindLabel[event.kind]}</span><strong>{event.title}</strong><p>{event.description}</p>{event.score!==undefined&&event.score!==null&&<span className="dossier-score">{event.score}% {event.status&&<Status value={event.status}/>}</span>}</div><button className="secondary" onClick={()=>open(event)}>{event.kind==='request'?'Abrir solicitud':'Abrir registro'}</button></div></li>)}</ol>:<p className="empty-copy">No hay actividad para los filtros seleccionados.</p>}{dossier.nextCursor&&<button className="secondary dossier-more" disabled={moreLoading} onClick={()=>void loadMore()}>{moreLoading?'Cargando actividad…':'Cargar actividad anterior'}</button>}</section></>:null}
 </section>;
}
