'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,ChartNoAxesCombined,ChevronsRight,ExternalLink,GitCompareArrows,Minus,RefreshCw} from 'lucide-react';
import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {compareNumericValues,descriptiveTrend,formatMetricValue,graphableMetricDefinitions,metricChangeLabels,type MetricChange,type MetricDefinition} from '@/lib/metric-definitions';
import './phase6-metrics.css';

type Point={visitId:string;visitDate:string;originalValue:string;numericValue:number;unit:string;responsible:string};
type History={metric:MetricDefinition;points:Point[];nextCursor:string|null};
type Comparison={metric:MetricDefinition;previous:{originalValue:string;numericValue?:number;textValue?:string;unit:string};current:{originalValue:string;numericValue?:number;textValue?:string;unit:string};comparison:{kind:'numeric'|'textual';change:string;delta?:number;relativeChange?:number|null;differenceLabel?:string;same?:boolean};};
type CompareResponse={previous:{id:string;date:string;responsible:string};current:{id:string;date:string;responsible:string};comparisons:Comparison[];onlyPrevious:string[];onlyCurrent:string[]};
type Range={from:string;to:string};

const definitions=graphableMetricDefinitions();
function dateText(value:string){return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`));}
function stateIcon(state:MetricChange){return state==='increased'?<ArrowUp size={16}/>:state==='decreased'?<ArrowDown size={16}/>:state==='stable'?<Minus size={16}/>:<ChevronsRight size={16}/>;}
function stateCopy(state:MetricChange){return metricChangeLabels[state];}
function uniquePoints(points:Point[]){const map=new Map(points.map(point=>[point.visitId,point]));return [...map.values()].sort((a,b)=>a.visitDate.localeCompare(b.visitDate)||a.visitId.localeCompare(b.visitId));}

function MetricDot({cx,cy,payload,onOpen}:{cx?:number;cy?:number;payload?:Point;onOpen:(id:string)=>void}){if(typeof cx!=='number'||typeof cy!=='number'||!payload)return null;return <a href={`#visita-${payload.visitId}`} aria-label={`Abrir visita del ${dateText(payload.visitDate)}`} onClick={event=>{event.preventDefault();onOpen(payload.visitId);}}><circle cx={cx} cy={cy} r={7} fill="#78be20" stroke="#fff" strokeWidth={2}/></a>;}

export default function FarmMetricEvolution({farmId,onOpenVisit}:{farmId:string;onOpenVisit:(id:string)=>void}){
 const [metricId,setMetricId]=useState(definitions[0]?.id||''),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(false),[moreLoading,setMoreLoading]=useState(false),[error,setError]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[range,setRange]=useState<Range>({from:'',to:''}),[visitA,setVisitA]=useState(''),[visitB,setVisitB]=useState(''),[comparison,setComparison]=useState<CompareResponse|null>(null),[compareLoading,setCompareLoading]=useState(false);
 const selected=definitions.find(definition=>definition.id===metricId)||definitions[0];
 const load=useCallback(async(cursor='',append=false)=>{if(!selected)return;if(append)setMoreLoading(true);else setLoading(true);setError('');try{const query=new URLSearchParams({metric:selected.id,limit:'30'});if(range.from)query.set('from',range.from);if(range.to)query.set('to',range.to);if(cursor)query.set('cursor',cursor);const response=await fetch(`/api/farms/${farmId}/metrics?${query}`),body=await response.json() as History&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo consultar la evolución.');setHistory(previous=>append&&previous?{...body,points:uniquePoints([...previous.points,...body.points])}:body);setComparison(null);}catch(reason){setError((reason as Error).message);}finally{if(append)setMoreLoading(false);else setLoading(false);}},[farmId,range,selected]);
 useEffect(()=>{const timer=window.setTimeout(()=>{setHistory(null);setVisitA('');setVisitB('');void load();},0);return()=>window.clearTimeout(timer);},[load]);
 const points=useMemo(()=>history?.points||[],[history]),latest=points.at(-1),previous=points.at(-2),change=latest&&previous&&selected?compareNumericValues(previous.numericValue,latest.numericValue,previous.unit,latest.unit,selected):null;
 const relativeChange=change&&'relativeChange' in change?change.relativeChange:null;
 const trend=selected?descriptiveTrend(points,selected):'insufficient_data';
 const candidates=useMemo(()=>points.slice().reverse(),[points]);
 const firstChoice=candidates[1]?.visitId||candidates[0]?.visitId||'',secondChoice=candidates[0]?.visitId||'';
 const selectedA=candidates.some(point=>point.visitId===visitA)?visitA:firstChoice,selectedB=candidates.some(point=>point.visitId===visitB)?visitB:secondChoice;
 const chart=useMemo(()=>points.map(point=>({...point,chartKey:`${point.visitDate}-${point.visitId}`})),[points]);
 async function compare(){if(!selectedA||!selectedB||selectedA===selectedB)return;setCompareLoading(true);setError('');try{const response=await fetch(`/api/farms/${farmId}/metrics/compare`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitAId:selectedA,visitBId:selectedB})}),body=await response.json() as CompareResponse&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudieron comparar las visitas.');setComparison(body);}catch(reason){setError((reason as Error).message);}finally{setCompareLoading(false);}}
 return <section className="farm-metric-evolution" aria-labelledby="evolution-title"><header><div><div className="eyebrow">EVOLUCIÓN</div><h3 id="evolution-title">Métricas históricas</h3><p>Los valores provienen de visitas revisadas. Cada punto abre su registro original.</p></div><div className="evolution-controls"><label className="evolution-selector">Métrica<select value={metricId} onChange={event=>setMetricId(event.target.value)}>{definitions.map(definition=><option key={definition.id} value={definition.id}>{definition.label}{definition.unit?` · ${definition.unit}`:''}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="secondary" onClick={()=>{if(from&&to&&from>to){setError('La fecha inicial no puede ser posterior a la final.');return;}setRange({from,to});}}>Aplicar</button></div></header>
 {error&&<p role="alert" className="notice error">{error}</p>}
 {loading?<output className="evolution-empty">Consultando mediciones…</output>:!selected||!history||!points.length?<div className="evolution-empty"><ChartNoAxesCombined size={25}/><strong>No hay mediciones para esta métrica.</strong><p>Registra un valor numérico y revisa la visita para incorporarlo al historial.</p></div>:<><div className="evolution-summary"><article><span>Último valor</span><b>{formatMetricValue(latest!.numericValue,selected)}</b><small>{dateText(latest!.visitDate)} · {latest!.responsible||'Responsable sin registrar'}</small></article><article><span>Valor anterior</span><b>{previous?formatMetricValue(previous.numericValue,selected):'—'}</b><small>{previous?dateText(previous.visitDate):'Solo existe una medición.'}</small></article><article><span>Cambio</span><b>{change&&change.change!=='incompatible'?change.differenceLabel:'Datos insuficientes'}</b><small>{relativeChange!==null?`Variación relativa: ${relativeChange>0?'+':''}${relativeChange} %`:'No aplica'}</small></article><article><span>Estado descriptivo</span><b className={`metric-change ${change&&change.change!=='incompatible'?change.change:'insufficient_data'}`}>{stateIcon(change&&change.change!=='incompatible'?change.change:'insufficient_data')}{stateCopy(change&&change.change!=='incompatible'?change.change:'insufficient_data')}</b><small>Tendencia: {stateCopy(trend)}{history.nextCursor?' en los datos cargados':''}</small></article></div>
 <div className="evolution-chart"><div><h4>Historial de {selected.label}</h4><p>Sin estimaciones ni valores intermedios.</p></div><div className="chart-scroll"><div style={{minWidth:Math.max(620,chart.length*105)}}><ResponsiveContainer width="100%" height={260}><LineChart data={chart} margin={{top:16,right:20,left:-8,bottom:3}}><XAxis dataKey="chartKey" tickFormatter={value=>dateText(String(value).slice(0,10))} tickLine={false} axisLine={false} minTickGap={28}/><YAxis tickLine={false} axisLine={false} tickFormatter={value=>formatMetricValue(Number(value),selected)}/><Tooltip labelFormatter={value=>dateText(String(value).slice(0,10))} formatter={(value)=>[formatMetricValue(Number(value),selected),'Valor']} contentStyle={{borderRadius:9,borderColor:'#b8d7dd'}}/><Line type="linear" name={selected.label} dataKey="numericValue" stroke="#007fa3" strokeWidth={3} connectNulls={false} isAnimationActive={false} dot={<MetricDot onOpen={onOpenVisit}/>} activeDot={{r:8,fill:'#007fa3'}}/></LineChart></ResponsiveContainer></div></div></div>
 <div className="evolution-history-heading"><div><h4>Historial tabular</h4><p>Valor original registrado en cada visita.</p></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={15}/>Actualizar</button></div><div className="table-scroll"><table className="followup-table metric-table evolution-table"><thead><tr><th>Fecha</th><th>Valor original</th><th>Unidad</th><th>Responsable</th><th className="no-print">Visita</th></tr></thead><tbody>{points.slice().reverse().map(point=><tr key={point.visitId}><td>{point.visitDate}</td><td><strong>{point.originalValue}</strong></td><td>{point.unit}</td><td>{point.responsible||'Sin registrar'}</td><td className="no-print"><button className="secondary" onClick={()=>onOpenVisit(point.visitId)}><ExternalLink size={15}/>Abrir</button></td></tr>)}</tbody></table></div>{history.nextCursor&&<button className="secondary evolution-more" disabled={moreLoading} onClick={()=>void load(history.nextCursor||'',true)}>{moreLoading?'Cargando…':'Cargar mediciones anteriores'}</button>}
 <section className="evolution-compare"><div><div className="eyebrow">COMPARAR VISITAS</div><h4>Comparación verificable</h4><p>Solo se comparan métricas presentes en las dos visitas de esta misma finca.</p></div><div className="evolution-compare-controls"><label>Visita A<select value={selectedA} onChange={event=>setVisitA(event.target.value)}>{candidates.map(point=><option key={point.visitId} value={point.visitId}>{dateText(point.visitDate)} · {point.originalValue}</option>)}</select></label><label>Visita B<select value={selectedB} onChange={event=>setVisitB(event.target.value)}>{candidates.map(point=><option key={point.visitId} value={point.visitId}>{dateText(point.visitDate)} · {point.originalValue}</option>)}</select></label><button className="primary" disabled={!selectedA||!selectedB||selectedA===selectedB||compareLoading} onClick={()=>void compare()}><GitCompareArrows size={16}/>{compareLoading?'Comparando…':'Comparar'}</button></div>{comparison&&<ComparisonTable value={comparison}/>}</section></>}
 </section>;
}

function ComparisonTable({value}:{value:CompareResponse}){return <div className="evolution-comparison-result"><p><strong>Anterior:</strong> {dateText(value.previous.date)} · <strong>Actual:</strong> {dateText(value.current.date)}</p>{value.comparisons.length?<div className="table-scroll"><table className="followup-table metric-table"><thead><tr><th>Métrica</th><th>Anterior</th><th>Actual</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>{value.comparisons.map(item=>{const numeric=item.comparison.kind==='numeric';const change=item.comparison.change as MetricChange;return <tr key={item.metric.id}><td>{item.metric.label}</td><td>{item.previous.originalValue}{item.previous.unit?` ${item.previous.unit}`:''}</td><td>{item.current.originalValue}{item.current.unit?` ${item.current.unit}`:''}</td><td>{numeric?item.comparison.differenceLabel||'—':item.comparison.same?'Sin cambios':'Texto distinto'}</td><td>{numeric?<span className={`metric-change ${change}`}>{change==='incompatible'?stateCopy('incompatible'):stateCopy(change)}</span>:'Sin tendencia'}</td></tr>;})}</tbody></table></div>:<p className="empty-copy">No existen métricas compatibles entre estas visitas.</p>}{(value.onlyPrevious.length||value.onlyCurrent.length)?<small className="muted">Las métricas que solo existen en una visita se omiten de la comparación.</small>:null}</div>}
