'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CalendarCheck2,Clock3,FileText,FolderSearch,MapPin,Search,TriangleAlert,Users} from 'lucide-react';
import type {Farm} from '@/lib/team';
import type {DossierEvent,DossierKind,FarmDossier} from '@/lib/farm-dossier';
import {metricStatusLabels} from '@/lib/model';
import {exportWord} from '@/lib/export-word';
import {reportStatusLabels,snapshotToVisit,type ReportVersion} from '@/lib/reports';
import FarmMetricEvolution from './farm-metric-evolution';

type Range={from:string;to:string};
const filters:{value:'all'|DossierKind;label:string}[]=[{value:'all',label:'Todos'},{value:'visit',label:'Visitas'},{value:'request',label:'Solicitudes'},{value:'report',label:'Informes'},{value:'photo',label:'Fotos'},{value:'followup',label:'Seguimientos'}];
const kindLabel:Record<DossierKind,string>={visit:'Visita técnica',request:'Solicitud',report:'Informe',photo:'Fotografías',followup:'Seguimiento'};
function dateText(value:string){if(!value)return 'Fecha por definir';return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`));}
function params(kind:'all'|DossierKind,range:Range,cursor=''){const result=new URLSearchParams({limit:'20'});if(kind!=='all')result.set('types',kind);if(range.from)result.set('from',range.from);if(range.to)result.set('to',range.to);if(cursor)result.set('cursor',cursor);return result;}
function EventIcon({kind}:{kind:DossierKind}){return kind==='report'?<FileText size={18}/>:kind==='followup'?<CalendarCheck2 size={18}/>:<Clock3 size={18}/>;}
function VersionPreview({version,onClose}:{version:ReportVersion;onClose:()=>void}){const snapshot=version.snapshot;if(!snapshot)return null;return <section className="report-snapshot dossier-version-preview"><div><div className="eyebrow">INFORME FORMAL</div><h3>Versión {version.versionNumber} · {reportStatusLabels[version.status]}</h3><p>{snapshot.farm.name} · {snapshot.content.date} · {snapshot.indicator.score===null?'Sin indicador':`${snapshot.indicator.score}%`}</p><p className="muted">Esta es la captura documental enviada a revisión. La visita original puede continuar su historial sin alterar esta versión.</p></div><div className="actions"><button className="primary" onClick={()=>void exportWord(snapshotToVisit(snapshot),snapshot)}>Descargar Word</button><button className="secondary" onClick={onClose}>Cerrar</button></div></section>;}

export default function FarmDossierPhase4({farms,onOpenVisit,onOpenRequest,onNew}:{farms:Farm[];onOpenVisit:(id:string)=>void;onOpenRequest:(id:string)=>void;onNew:(farm:Farm)=>void}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[dossier,setDossier]=useState<FarmDossier|null>(null),[kind,setKind]=useState<'all'|DossierKind>('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[range,setRange]=useState<Range>({from:'',to:''}),[loading,setLoading]=useState(false),[moreLoading,setMoreLoading]=useState(false),[error,setError]=useState(''),[report,setReport]=useState<ReportVersion|null>(null);const version=useRef(0);
 const selectedFarm=farms.find(farm=>farm.id===selected),matches=query.trim()?farms.filter(farm=>farm.name.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es'))):[];
 useEffect(()=>{if(!selected)return;let current=true;const timer=window.setTimeout(()=>{const request=++version.current;setLoading(true);setError('');fetch(`/api/farms/${selected}/dossier?${params(kind,range).toString()}`).then(async response=>{const body=await response.json() as FarmDossier&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo consultar el expediente.');return body;}).then(value=>{if(current&&request===version.current)setDossier(value);}).catch(reason=>{if(current)setError((reason as Error).message);}).finally(()=>{if(current)setLoading(false);});},0);return()=>{current=false;window.clearTimeout(timer);};},[selected,kind,range]);
 function choose(farm:Farm){setSelected(farm.id);setQuery(farm.name);setKind('all');setRange({from:'',to:''});setFrom('');setTo('');setDossier(null);setReport(null);}
 async function loadMore(){if(!dossier?.nextCursor||!selected)return;setMoreLoading(true);setError('');try{const response=await fetch(`/api/farms/${selected}/dossier?${params(kind,range,dossier.nextCursor).toString()}`),body=await response.json() as FarmDossier&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo cargar más actividad.');setDossier(previous=>previous?{...body,events:[...previous.events,...body.events]}:body);}catch(reason){setError((reason as Error).message);}finally{setMoreLoading(false);}}
 async function open(event:DossierEvent){if(event.reportVersionId){try{setError('');const response=await fetch(`/api/reports/${event.reportVersionId}`),body=await response.json() as ReportVersion&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo abrir esta versión.');setReport(body);return;}catch(reason){setError((reason as Error).message);return;}}if(event.visitId)onOpenVisit(event.visitId);else if(event.requestId)onOpenRequest(event.requestId);}
 return <section className="farm-dossier" aria-labelledby="dossier-title"><div className="dossier-hero"><div><div className="eyebrow">EXPEDIENTE TÉCNICO</div><h2 id="dossier-title">Consulta de finca</h2><p>Una historia cronológica de solicitudes, visitas, informes, fotografías y compromisos, sin duplicar los registros originales.</p></div><div className="dossier-search"><label htmlFor="dossier-search">Buscar finca</label><div><Search size={20}/><input id="dossier-search" value={query} placeholder="Escribe el nombre de una finca" onChange={event=>{setQuery(event.target.value);if(selected&&event.target.value!==selectedFarm?.name)setSelected('');}}/></div>{query&&!selected&&<div className="dossier-matches">{matches.length?matches.map(farm=><button key={farm.id} onClick={()=>choose(farm)}><span>{farm.name}<small>{farm.zone||'Zona sin registrar'}</small></span><ArrowRight size={16}/></button>):<p>No hay fincas registradas que coincidan.</p>}</div>}</div></div>
 {!selected?<div className="dossier-empty"><FolderSearch size={30}/><strong>Elige una finca para abrir su expediente</strong><p>Solo aparecen fincas registradas a las que tienes acceso.</p>{!query&&farms.slice(0,6).map(farm=><button className="secondary" key={farm.id} onClick={()=>choose(farm)}>{farm.name}</button>)}</div>:loading&&!dossier?<output className="dossier-empty"><Clock3 size={30}/><strong>Preparando el expediente…</strong><p>Se carga una página de actividad, no todo el historial.</p></output>:selectedFarm&&dossier?<><header className="dossier-heading"><div><div className="eyebrow">FINCA</div><h3>{dossier.farm.name}</h3><p><MapPin size={16}/>{dossier.farm.zone||'Zona sin registrar'}</p></div><div className="dossier-heading-actions"><button className="primary" onClick={()=>onNew(selectedFarm)}><FileText size={17}/>Nuevo informe</button><span><Users size={16}/>{selectedFarm.members.length} participante{selectedFarm.members.length===1?'':'s'}</span></div></header>
 <div className="dossier-stats"><article><span>Última visita revisada</span><b>{dossier.summary.latestVisit?dateText(dossier.summary.latestVisit.date):'—'}</b><small>{dossier.summary.latestVisit?.responsible||'Sin informe revisado'}</small></article><article><span>Visitas registradas</span><b>{dossier.summary.visits}</b><small>{dossier.summary.photos} fotografías asociadas</small></article><article><span>Solicitudes abiertas</span><b>{dossier.summary.openRequests}</b><small>Solicitadas o programadas</small></article><article><span>Informes revisados</span><b>{dossier.summary.reports}</b><small>Derivados de visitas revisadas</small></article><article><span>Compromisos activos</span><b>{dossier.summary.pendingFollowups}</b><small>{dossier.summary.overdueFollowups} vencido{dossier.summary.overdueFollowups===1?'':'s'}</small></article><article><span>Cierres recientes</span><b>{dossier.summary.recentCompletedFollowups}</b><small>Completados en los últimos 30 días</small></article></div>
 <section className="dossier-current"><div><div className="eyebrow">SITUACIÓN ACTUAL</div><h3>{dossier.summary.latestVisit?.score===null||!dossier.summary.latestVisit?'Sin medición revisada':`${dossier.summary.latestVisit.score}%`}</h3><p>{dossier.summary.latestVisit?metricStatusLabels[dossier.summary.latestVisit.status]:'Registra y revisa un aseguramiento para calcular el indicador.'}</p></div><p>{dossier.summary.overdueFollowups?<><TriangleAlert size={17}/> Hay {dossier.summary.overdueFollowups} compromiso{dossier.summary.overdueFollowups===1?'':'s'} vencido{dossier.summary.overdueFollowups===1?'':'s'} que requiere{dossier.summary.overdueFollowups===1?'':'n'} atención.</>:dossier.summary.pendingFollowups?'Los compromisos activos continúan en seguimiento.':'No hay compromisos activos en esta finca.'}</p></section>
 <FarmMetricEvolution farmId={selected} onOpenVisit={onOpenVisit}/>
 <section className="dossier-activity"><div className="dossier-activity-heading"><div><div className="eyebrow">ACTIVIDAD RECIENTE</div><h3>Línea de tiempo</h3><p>Abre cada elemento para consultar su registro original o la captura formal del informe.</p></div><div className="dossier-range"><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="secondary" onClick={()=>setRange({from,to})}>Aplicar</button></div></div><div className="dossier-filters" aria-label="Filtrar actividad">{filters.map(filter=><button key={filter.value} className={kind===filter.value?'active':''} onClick={()=>setKind(filter.value)}>{filter.label}</button>)}</div>{error&&<p role="alert" className="notice error">{error}</p>}{report&&<VersionPreview version={report} onClose={()=>setReport(null)}/>} {dossier.events.length?<ol className="dossier-timeline">{dossier.events.map(event=><li key={event.id}><time>{dateText(event.occurredOn)}</time><div className={'dossier-event '+event.kind}><div className="dossier-event-icon"><EventIcon kind={event.kind}/></div><div><span className="dossier-kind">{kindLabel[event.kind]}</span><strong>{event.title}</strong><p>{event.description}</p>{event.score!==undefined&&event.score!==null&&<span className="dossier-score">{event.score}% · {event.status&&metricStatusLabels[event.status]}</span>}</div><button className="secondary" onClick={()=>void open(event)}>{event.kind==='request'?'Abrir solicitud':event.reportVersionId?'Abrir versión':'Abrir registro'}</button></div></li>)}</ol>:<p className="empty-copy">No hay actividad para los filtros seleccionados.</p>}{dossier.nextCursor&&<button className="secondary dossier-more" disabled={moreLoading} onClick={()=>void loadMore()}>{moreLoading?'Cargando actividad…':'Cargar actividad anterior'}</button>}</section></>:null}
 </section>;
}
