'use client';
import {useEffect,useState} from 'react';
import {CalendarClock,CheckCircle2,CircleAlert,ListTodo,Save,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import ListPager from './list-pager';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {findings,overdue,farmKey,compareVisits,actionLabels,localDate,type Visit,type Action,type ActionStatus} from '@/lib/model';
import type {Farm} from '@/lib/team';

type FollowupProps={visits:Visit[];loading:boolean;busy:boolean;onOpen:(v:Visit)=>void;desktop?:boolean;farms?:Farm[];onOpenId?:(id:string)=>void};
type Commitment={id:string;visitId:string;criterionId:string;revision:number;farmId:string|null;farm:string;visitDate:string;technician:string;description:string;recommendation:string;action:Action;canEdit:boolean};
type CommitmentResponse={today:string;dueSoonDays:number;summary:{today:number;upcoming:number;overdue:number;completed:number;pending:number};items:Commitment[];nextCursor:string|null};
type Draft={item:Commitment;owner:string;due:string;status:ActionStatus;closure:string};

function commitmentParams(values:{farmId:string;responsible:string;technician:string;status:string;bucket:string;from:string;to:string;cursor?:string}){const result=new URLSearchParams({limit:'20',bucket:values.bucket,status:values.status});for(const [key,value] of Object.entries(values))if(value&&key!=='cursor')result.set(key,value);if(values.cursor)result.set('cursor',values.cursor);return result;}
function bucketEmpty(bucket:string){return bucket==='today'?'No hay compromisos para hoy.':bucket==='upcoming'?'No hay compromisos que venzan pronto.':bucket==='overdue'?'No hay compromisos vencidos.':bucket==='completed'?'No hay compromisos completados para estos filtros.':'No hay compromisos para estos filtros.';}

function OnlineFollowup({farms,busy,onOpenId,onOpen}:Pick<FollowupProps,'farms'|'busy'|'onOpenId'|'onOpen'>){
 const [farmId,setFarmId]=useState(''),[responsible,setResponsible]=useState(''),[technician,setTechnician]=useState(''),[status,setStatus]=useState('all'),[bucket,setBucket]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<CommitmentResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[moreLoading,setMoreLoading]=useState(false),[draft,setDraft]=useState<Draft|null>(null),[saving,setSaving]=useState(false),[version,setVersion]=useState(0),[availableFarms,setAvailableFarms]=useState<Farm[]>([]);
 useEffect(()=>{if(farms?.length)return;let current=true;fetch('/api/team').then(async response=>{const body=await response.json() as {farms?:Farm[]};if(!response.ok)throw new Error();return body.farms||[];}).then(items=>{if(current)setAvailableFarms(items);}).catch(()=>{});return()=>{current=false;};},[farms]);
 useEffect(()=>{let current=true;const timer=window.setTimeout(()=>{setLoading(true);setError('');fetch(`/api/commitments?${commitmentParams({farmId,responsible,technician,status,bucket,from,to}).toString()}`).then(async response=>{const body=await response.json() as CommitmentResponse&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo consultar el seguimiento.');return body;}).then(result=>{if(current)setData(result);}).catch(reason=>{if(current)setError((reason as Error).message);}).finally(()=>{if(current)setLoading(false);});},0);return()=>{current=false;window.clearTimeout(timer);};},[farmId,responsible,technician,status,bucket,from,to,version]);
 async function loadMore(){if(!data?.nextCursor)return;setMoreLoading(true);setError('');try{const response=await fetch(`/api/commitments?${commitmentParams({farmId,responsible,technician,status,bucket,from,to,cursor:data.nextCursor}).toString()}`),body=await response.json() as CommitmentResponse&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo cargar más compromisos.');setData(previous=>previous?{...body,items:[...previous.items,...body.items]}:body);}catch(reason){setError((reason as Error).message);}finally{setMoreLoading(false);}}
 async function saveDraft(){if(!draft)return;setSaving(true);setError('');try{const response=await fetch('/api/commitments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitId:draft.item.visitId,criterionId:draft.item.criterionId,revision:draft.item.revision,action:{owner:draft.owner,due:draft.due,status:draft.status,closure:draft.closure}})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'No se pudo actualizar el compromiso.');setDraft(null);setVersion(value=>value+1);}catch(reason){setError((reason as Error).message);}finally{setSaving(false);}}
 async function openOriginal(visitId:string){if(onOpenId){onOpenId(visitId);return;}try{const response=await fetch(`/api/visits/${encodeURIComponent(visitId)}`),body=await response.json() as Visit&{error?:string};if(!response.ok)throw new Error(body.error||'No se pudo abrir la visita.');onOpen(body);}catch(reason){setError((reason as Error).message);}}
 const cards=[{id:'today',label:'Hoy',value:data?.summary.today||0,icon:CalendarClock},{id:'upcoming',label:`Próximos ${data?.dueSoonDays||7} días`,value:data?.summary.upcoming||0,icon:ListTodo},{id:'overdue',label:'Vencidos',value:data?.summary.overdue||0,icon:CircleAlert},{id:'completed',label:'Completados',value:data?.summary.completed||0,icon:CheckCircle2}] as const, farmOptions=farms?.length?farms:availableFarms;
 return <section className="followup-panel commitments-online" aria-labelledby="followup-title"><div className="page-heading"><div><div className="eyebrow">SEGUIMIENTO OPERATIVO</div><h2 id="followup-title">Compromisos por finca</h2><p>Consulta, actualiza y cierra compromisos sin modificar ni duplicar la visita que los originó.</p></div></div>
 <div className="commitment-cards">{cards.map(card=><button key={card.id} className={bucket===card.id?'active':''} onClick={()=>setBucket(card.id)}><card.icon size={19}/><span>{card.label}</span><b>{loading?'—':card.value}</b></button>)}</div>
 <div className="fields commitment-filters"><label>Finca<Select value={farmId||'all'} onValueChange={value=>setFarmId(value==='all'?'':String(value))} items={[{value:'all',label:'Todas las fincas'},...farmOptions.map(farm=>({value:farm.id,label:farm.name}))]}><SelectTrigger aria-label="Filtrar compromisos por finca"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas las fincas</SelectItem>{farmOptions.map(farm=><SelectItem key={farm.id} value={farm.id}>{farm.name}</SelectItem>)}</SelectContent></Select></label><label>Responsable<input value={responsible} maxLength={300} placeholder="Nombre asignado" onChange={event=>setResponsible(event.target.value)}/></label><label>Técnico AVGUST<input value={technician} maxLength={300} placeholder="Responsable de visita" onChange={event=>setTechnician(event.target.value)}/></label><label>Estado<Select value={status} onValueChange={value=>setStatus(String(value))} items={[{value:'all',label:'Todos los estados'},...Object.entries(actionLabels).map(([value,label])=>({value,label}))]}><SelectTrigger aria-label="Filtrar compromisos por estado"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los estados</SelectItem>{Object.entries(actionLabels).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div>
 <div className="dossier-filters" aria-label="Secciones de compromisos"><button className={bucket==='all'?'active':''} onClick={()=>setBucket('all')}>Todos</button>{cards.map(card=><button key={card.id} className={bucket===card.id?'active':''} onClick={()=>setBucket(card.id)}>{card.label}</button>)}</div>
 {error&&<p role="alert" className="notice error">{error}</p>}{loading&&!data?<p role="status" className="empty-copy">Consultando compromisos…</p>:<>{data?.items.length?<div className="table-scroll"><table className="followup-table"><thead><tr><th>Finca / hallazgo</th><th>Responsable</th><th>Fecha objetivo</th><th>Estado</th><th>Origen</th><th>Acción</th></tr></thead><tbody>{data.items.map(item=>{const late=item.action.status!=='closed'&&item.action.status!=='cancelled'&&Boolean(item.action.due)&&item.action.due<data.today;return <tr key={item.id}><td><strong>{item.farm} · {item.criterionId}</strong><span>{item.description}</span><small>{item.recommendation||'Sin recomendación registrada'}</small></td><td>{item.action.owner||'Sin asignar'}</td><td className={late?'deadline':''}>{item.action.due||'Sin fecha'}</td><td>{late?'Vencido · ':''}{actionLabels[item.action.status]}{item.action.completedAt&&<small> Cerrado {item.action.completedAt.slice(0,10)}</small>}</td><td><button className="secondary" disabled={busy} onClick={()=>void openOriginal(item.visitId)}>Visita {item.visitDate}</button></td><td><div className="table-actions">{item.canEdit&&<button className="secondary" disabled={busy} onClick={()=>setDraft({item,owner:item.action.owner,due:item.action.due,status:item.action.status,closure:item.action.closure})}>Actualizar</button>}</div></td></tr>;})}</tbody></table></div>:<p className="empty-copy">{bucketEmpty(bucket)}</p>}{data?.nextCursor&&<button className="secondary dossier-more" disabled={moreLoading} onClick={()=>void loadMore()}>{moreLoading?'Cargando compromisos…':'Cargar compromisos anteriores'}</button>}</>}
 {draft&&<section className="commitment-editor"><div><div className="eyebrow">ACTUALIZAR COMPROMISO</div><h3>{draft.item.farm} · {draft.item.criterionId}</h3><p>La visita original se conserva; el cierre queda trazado junto a este hallazgo.</p></div><button className="icon-button" aria-label="Cerrar edición" onClick={()=>setDraft(null)}><X size={18}/></button><div className="fields"><label>Responsable<input maxLength={300} value={draft.owner} onChange={event=>setDraft({...draft,owner:event.target.value})}/></label><label>Fecha objetivo<input type="date" value={draft.due} onChange={event=>setDraft({...draft,due:event.target.value})}/></label><label>Estado<Select value={draft.status} onValueChange={value=>setDraft({...draft,status:value as ActionStatus})} items={Object.entries(actionLabels).map(([value,label])=>({value,label}))}><SelectTrigger aria-label="Estado del compromiso"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(actionLabels).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label></div><label>Comentario de seguimiento o cierre<textarea maxLength={12000} value={draft.closure} onChange={event=>setDraft({...draft,closure:event.target.value})}/></label>{draft.status==='closed'&&<p className="muted">Para completar se requieren responsable, fecha objetivo y comentario. La evidencia fotográfica es opcional y se selecciona desde la visita original.</p>}<div className="actions"><button className="primary" disabled={saving} onClick={()=>void saveDraft()}><Save size={17}/>{saving?'Guardando…':'Guardar seguimiento'}</button><button className="secondary" disabled={saving} onClick={()=>setDraft(null)}>Cancelar</button></div></section>}
 </section>;
}

export function ActionEditor({v,id,onChange}:{v:Visit;id:string;onChange:(a:Action)=>void}){
 const a=v.actions?.[id]||{owner:'',due:'',status:'proposed',closure:'',beforePhotoId:'',photoId:''};
 const options=[{value:'none',label:'Selecciona una fotografía'},...v.photos.filter(p=>p.chapter===Number(id.split('.')[0])).map(p=>({value:p.id,label:p.caption||'Fotografía sin descripción'}))];
 return <div className="action-editor"><h4>Plan de acción · {id}</h4><div className="fields">
 <label>Responsable del compromiso<input maxLength={300} value={a.owner} onChange={e=>onChange({...a,owner:e.target.value})}/></label>
 <label>Fecha límite<input type="date" value={a.due} onChange={e=>onChange({...a,due:e.target.value})}/></label>
 <label>Estado<Select value={a.status} onValueChange={s=>s&&onChange({...a,status:s as Action['status']})} items={Object.entries(actionLabels).map(([value,label])=>({value,label}))}><SelectTrigger aria-label={`Estado del hallazgo ${id}`}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(actionLabels).map(([s,l])=><SelectItem key={s} value={s}>{l}</SelectItem>)}</SelectContent></Select></label>
 <label>Fotografía inicial / antes<Select value={a.beforePhotoId||'none'} onValueChange={s=>s&&onChange({...a,beforePhotoId:s==='none'?'':String(s)})} items={options}><SelectTrigger aria-label={`Evidencia inicial del hallazgo ${id}`}><SelectValue/></SelectTrigger><SelectContent>{options.map(p=><SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}</SelectContent></Select></label>
 <label>Fotografía de cierre<Select value={a.photoId||'none'} onValueChange={s=>s&&onChange({...a,photoId:s==='none'?'':String(s)})} items={options}><SelectTrigger aria-label={`Evidencia del hallazgo ${id}`}><SelectValue/></SelectTrigger><SelectContent>{options.map(p=><SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}</SelectContent></Select></label>
 </div><label>Nota de seguimiento / cierre<textarea maxLength={12000} value={a.closure} onChange={e=>onChange({...a,closure:e.target.value})}/></label><p className="muted">Para mostrar el antes y después, adjunta dos fotos del mismo capítulo y selecciónalas aquí. Para cerrar, completa responsable, fecha, nota y evidencia de cierre.</p>{overdue(a)&&<p className="deadline">Compromiso vencido</p>}</div>;
}

function LocalFollowup({visits,loading,busy,onOpen}:{visits:Visit[];loading:boolean;busy:boolean;onOpen:(v:Visit)=>void}){
 const [view,setView]=useState('commitments'),[page,setPage]=useState(0);
 const [farm,setFarm]=useState(''),[status,setStatus]=useState('open');const today=localDate();
 const farms=Array.from(new Map(visits.map(v=>[v.farmId||farmKey(v.farm),v.farm])).entries()).sort((a,b)=>a[1].localeCompare(b[1],'es'));
 const scope=visits.filter(v=>!farm||(v.farmId||farmKey(v.farm))===farm);
 const all=scope.flatMap(v=>findings(v).map(f=>({...f,visit:v})));
 const pending=all.filter(f=>['pending','progress'].includes(f.action.status)),late=pending.filter(f=>overdue(f.action,today));
 const rows=all.filter(f=>status==='all'||status==='proposed'&&f.action.status==='proposed'||status==='late'&&overdue(f.action,today)||status==='closed'&&f.action.status==='closed'||status==='open'&&['pending','progress'].includes(f.action.status)).sort((a,b)=>(a.action.due||'9999').localeCompare(b.action.due||'9999'));
 useEffect(()=>{const timer=window.setTimeout(()=>setPage(0));return()=>window.clearTimeout(timer);},[farm,status,visits]);
 const history=farm?[...scope].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id)):[];
 const latest=history[0];const previous=latest?history.find(v=>v.date<latest.date):undefined;
 const unambiguous=latest&&previous&&history.filter(v=>v.date===latest.date).length===1&&history.filter(v=>v.date===previous.date).length===1;
 const comparison=unambiguous?compareVisits(previous,latest):[];
 return <section className="followup-panel" aria-labelledby="followup-title"><div className="page-heading"><div><div className="eyebrow">SEGUIMIENTO DE FINCAS</div><h2 id="followup-title">De los hallazgos a los resultados</h2><p>Compromisos de las visitas guardadas. Abre una visita para actualizar su plan.</p></div></div>
 <Tabs value={view} onValueChange={s=>setView(String(s))}><TabsList className="module-subtabs"><TabsTrigger value="commitments">Compromisos</TabsTrigger><TabsTrigger value="agenda">Agenda y revisión</TabsTrigger><TabsTrigger value="history">Historial por finca</TabsTrigger></TabsList><div className="fields"><label>Finca<Select value={farm||'all'} onValueChange={s=>setFarm(s==='all'?'':String(s))} items={[{value:'all',label:'Todas las fincas'},...farms.map(([value,label])=>({value,label}))]}><SelectTrigger aria-label="Filtrar por finca"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas las fincas</SelectItem>{farms.map(([k,n])=><SelectItem key={k} value={k}>{n}</SelectItem>)}</SelectContent></Select></label>
 <label hidden={view!=='commitments'}>Mostrar compromisos<Select value={status} onValueChange={s=>s&&setStatus(String(s))} items={[{value:'open',label:'Pendientes y en proceso'},{value:'late',label:'Vencidos'},{value:'closed',label:'Cerrados'},{value:'proposed',label:'Recomendaciones propuestas'},{value:'all',label:'Todos'}]}><SelectTrigger aria-label="Filtrar compromisos"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="open">Pendientes y en proceso</SelectItem><SelectItem value="late">Vencidos</SelectItem><SelectItem value="closed">Cerrados</SelectItem><SelectItem value="proposed">Recomendaciones propuestas</SelectItem><SelectItem value="all">Todos</SelectItem></SelectContent></Select></label></div>
 {loading?<p role="status">Cargando seguimiento…</p>:<><TabsContent value="commitments"><div className="followup-stats"><div><b>{pending.length}</b>Pendientes / en proceso</div><div className="deadline"><b>{late.length}</b>Vencidos</div><div><b>{all.filter(f=>f.action.status==='closed').length}</b>Cerrados</div><div><b>{new Set(pending.map(f=>f.visit.farmId||farmKey(f.visit.farm))).size}</b>Fincas con pendientes</div></div>
 <p className="muted">Las propuestas no cuentan como compromisos pendientes ni vencidos. Cada compromiso aceptado pertenece a su visita original. Una nueva evaluación no cierra automáticamente compromisos anteriores.</p>
 {rows.length?<div className="table-scroll"><table className="followup-table"><thead><tr><th>Finca / hallazgo</th><th>Responsable</th><th>Fecha límite</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{rows.slice(page*8,page*8+8).map(f=><tr key={`${f.visit.id}-${f.id}`}><td><strong>{f.visit.farm} · {f.id}</strong><span>{f.answer.observation||f.text}</span><small>Visita {f.visit.date}</small></td><td>{f.action.owner||'Sin asignar'}</td><td className={overdue(f.action,today)?'deadline':''}>{f.action.due||'Sin fecha'}</td><td>{overdue(f.action,today)?'Vencido · ':''}{actionLabels[f.action.status]}</td><td><button className="secondary" disabled={busy} onClick={()=>onOpen(f.visit)}>Abrir visita</button></td></tr>)}</tbody></table></div>:<p className="empty-copy">No hay compromisos para este filtro.</p>}
 <ListPager page={page} total={rows.length} onChange={setPage}/></TabsContent><TabsContent value="agenda"><div className="fields section-gap"><section><h3>Seguimientos programados</h3>{scope.filter(v=>v.followup).length?scope.filter(v=>v.followup).sort((a,b)=>a.followup.localeCompare(b.followup)).map(v=><div className="visit-row" key={v.id}><div><strong>{v.farm}</strong><small>{v.followup}{v.followup<today?' · Fecha pasada':''}</small></div><button className="secondary" disabled={busy} onClick={()=>onOpen(v)}>Abrir</button></div>):<p className="muted">No hay fechas de seguimiento registradas.</p>}</section><section><h3>Informes por revisar</h3>{scope.some(v=>!v.reviewed)?scope.filter(v=>!v.reviewed).map(v=><div className="visit-row" key={v.id}><div><strong>{v.farm}</strong><small>{v.date}</small></div><button className="secondary" disabled={busy} onClick={()=>onOpen(v)}>Revisar</button></div>):<p className="muted">No hay borradores pendientes.</p>}</section></div>
 </TabsContent><TabsContent value="history"><section className="section-gap"><h3>Historial por finca</h3>{!farm?<p className="muted">Selecciona una finca para ver sus visitas y comparar resultados.</p>:<>{unambiguous&&previous&&latest?<><p>Comparación: {previous.date} → {latest.date}</p><p className="muted">Solo “Sí” cuenta como corregido. “No aplica” y los criterios sin evaluar se muestran por separado. Las visitas del mismo día no se ordenan como antes/después.</p>{comparison.length?<ul className="comparison-list">{comparison.map(f=><li key={f.id}><strong>{f.id} · {f.result}</strong><span>{f.text}</span></li>)}</ul>:<p>La visita anterior no tenía respuestas “No”.</p>}</>:<p className="muted">La comparación requiere dos fechas distintas con una sola visita en cada fecha. Consulta las visitas abajo si hay varias el mismo día.</p>}{history.map(v=><div className="visit-row" key={v.id}><div><strong>{v.date} · {v.responsible}</strong><small>{findings(v).length} hallazgos · {findings(v).filter(f=>f.action.status==='closed').length} compromisos cerrados · {v.reviewed?'Revisado':'Borrador'}</small></div><button className="secondary" disabled={busy} onClick={()=>onOpen(v)}>Abrir</button></div>)}</>}</section></TabsContent></>}
 </Tabs></section>;
}

export default function Followup({desktop=false,farms,onOpenId,...props}:FollowupProps){
 return desktop||(typeof window!=='undefined'&&Boolean(window.careDesktop))?<LocalFollowup {...props}/>:<OnlineFollowup farms={farms} busy={props.busy} onOpen={props.onOpen} onOpenId={onOpenId}/>;
}
