'use client';
import {useMemo,useState} from 'react';
import {Download,FileText,Printer,TrendingDown,TrendingUp} from 'lucide-react';
import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {farmKey,metricStatusLabels,metricTrendLabels,type MetricStatus,type Visit} from '@/lib/model';
import {exportFarmMetricsWord} from '@/lib/export-metrics-word';
import {farmMetricHistory} from '@/lib/metric-analysis';
import {FarmChapterDetails} from './metric-chapter-details';
import ConsolidatedMetrics from './consolidated-metrics';

function Status({value}:{value:MetricStatus}){return <span className={'metric-status '+value}>{metricStatusLabels[value]}</span>;}
function changeCopy(delta:number|null){return delta===null?'Sin comparación':`${delta>0?'+':''}${delta} puntos desde la primera medición`;}

function FarmMetrics({visits,loading,onOpen}:{visits:Visit[];loading:boolean;onOpen:(visit:Visit)=>void}){
 const farms=useMemo(()=>Array.from(new Map(visits.map(v=>[farmKey(v.farm),v.farm.trim()])).entries()).filter(([,name])=>name).sort((a,b)=>a[1].localeCompare(b[1],'es')),[visits]);
 const [farm,setFarm]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');
 const activeFarm=farm||farms[0]?.[0]||'';
 const scoped=useMemo(()=>visits.filter(v=>(!from||v.date>=`${from}-01-01`)&&(!to||v.date<=`${to}-12-31`)),[visits,from,to]);
 const data=useMemo(()=>farmMetricHistory(scoped,activeFarm),[scoped,activeFarm]);
 const chart=data.records.map(r=>({label:new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${r.date}T12:00:00`)),score:r.score,hallazgos:r.findings}));
 const current=data.latest;
 return <section className="metrics-panel" aria-labelledby="farm-metrics-title"><div className="metrics-print-brand"><img src="/avgust-logo.svg" alt="Avgust Crop Protection"/><div><strong>AVGUST CARE 360</strong><span>Informe de evolución por finca</span></div></div><div className="page-heading"><div><div className="eyebrow">HISTORIAL DE INDICADORES</div><h2 id="farm-metrics-title">Evolución de la finca</h2><p>Cada informe revisado se conserva como una medición independiente. El indicador oficial sigue la fórmula 1.5.35; el análisis ponderado es solo complementario.</p></div>{current&&<div className="metrics-actions no-print"><button className="secondary" onClick={()=>void exportFarmMetricsWord(data)}><FileText size={17}/>Descargar Word</button><button className="primary" onClick={()=>window.print()}><Printer size={17}/>Guardar PDF con gráfica</button></div>}</div>
 <div className="metrics-filters no-print"><label>Finca<Select value={activeFarm||'none'} onValueChange={value=>setFarm(value==='none'?'':String(value))} items={[{value:'none',label:'Selecciona una finca'},...farms.map(([id,name])=>({value:id,label:name}))]}><SelectTrigger aria-label="Finca para consultar métricas"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Selecciona una finca</SelectItem>{farms.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></label><label>Desde<input type="number" min="2020" max="2100" placeholder="2022" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="number" min="2020" max="2100" placeholder="2026" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 {loading?<p role="status">Cargando métricas…</p>:!farms.length?<p className="empty-copy">Aún no hay visitas guardadas para calcular métricas.</p>:!current?<div className="notice">Esta finca no tiene informes revisados con criterios aplicables en el periodo seleccionado.</div>:<><div className="metric-summary farm-metric-summary"><div><span>Indicador oficial</span><b>{current.score}%</b><Status value={current.status}/></div><div><span>Comportamiento</span><b className={'trend '+data.trend}>{data.trend==='improved'?<TrendingUp size={23}/>:data.trend==='declined'?<TrendingDown size={23}/>:null}{metricTrendLabels[data.trend]}</b><small>{changeCopy(data.delta)}</small></div><div><span>Última evaluación</span><b>{current.date}</b><small>{current.responsible||'Responsable sin registrar'}</small></div><div><span>Hallazgos actuales</span><b>{current.findings}</b><small>de {current.applicable} criterios aplicables</small></div><div><span>Ponderado complementario</span><b>{current.weightedScore===null?'—':`${current.weightedScore}%`}</b><small>{current.evaluatedChapters}/5 capítulos · {current.weightedCoveragePct}% del peso MIPE</small></div></div>
 <div className="metric-chart"><div><h3>Comportamiento en el tiempo</h3><p>Indicador de cumplimiento por visita revisada.</p></div><div className="chart-scroll"><div style={{minWidth:Math.max(620,chart.length*115)}}><ResponsiveContainer width="100%" height={280}><LineChart data={chart} margin={{top:15,right:16,left:-15,bottom:4}}><XAxis dataKey="label" tickLine={false} axisLine={false} minTickGap={25}/><YAxis domain={[0,100]} tickLine={false} axisLine={false} tickFormatter={v=>`${v}%`}/><Tooltip formatter={(value,name)=>[`${value}%`,name==='score'?'Indicador':'Hallazgos']}/><Line type="linear" name="Indicador" dataKey="score" stroke="#007fa3" strokeWidth={3} dot={{r:5,fill:'#78be20'}} activeDot={{r:7}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></div></div>
 <div className="metric-grid section-gap"><section><h3>Cierre por año</h3><div className="metric-year-grid">{data.yearly.map(y=><div key={y.year}><span>{y.year}</span><b>{y.closing}%</b><Status value={y.status}/><small>Promedio {y.average}% · {y.visits} visita{y.visits===1?'':'s'}</small></div>)}</div></section><section><h3>Estado por capítulo</h3><p className="muted">Abre un capítulo para comparar la primera y última medición por subcapítulo.</p><FarmChapterDetails chapters={data.chapters}/></section></div>
 <section className="metric-problems section-gap"><div><div className="eyebrow">ALERTAS TÉCNICAS</div><h3>Problemas identificados en la última visita</h3></div>{data.problems.length?<div className="metric-problem-grid">{data.problems.map(problem=><article key={problem.id}><span>{problem.id} · Capítulo {problem.chapter}</span><h4>{problem.text}</h4><p>{problem.recommendation}</p><small className={problem.occurrences>1?'recurrent':''}>{problem.occurrences>1?`Recurrente en ${problem.occurrences} informes`: 'Detectado en la última visita'}</small></article>)}</div>:<p className="metric-clear">La última visita no registra problemas abiertos en los capítulos evaluados.</p>}</section>
 <h3 className="section-gap">Historial de informes revisados</h3><div className="table-scroll"><table className="followup-table metric-table"><thead><tr><th>Fecha</th><th>Indicador oficial</th><th>Ponderado comp.</th><th>Estado</th><th>Comportamiento</th><th>Responsable</th><th>Hallazgos</th><th className="no-print"></th></tr></thead><tbody>{data.records.slice().reverse().map((record,index)=>{const prior=data.records[data.records.length-index-2];const difference=prior?record.score-prior.score:0;return <tr key={record.visit.id}><td>{record.date}</td><td><strong>{record.score}%</strong><small>{record.positive}/{record.applicable} positivos</small></td><td><strong>{record.weightedScore===null?'—':`${record.weightedScore}%`}</strong><small>{record.evaluatedChapters}/5 capítulos · {record.weightedCoveragePct}% peso</small></td><td><Status value={record.status}/></td><td><span className={'trend '+(difference>=5?'improved':difference<=-5?'declined':'stable')}>{index===data.records.length-1?'Primera medición':difference>=5?'Aumentó':difference<=-5?'Disminuyó':'Estable'}</span></td><td>{record.responsible||'Sin registrar'}</td><td>{record.findings}</td><td className="no-print"><button className="secondary" onClick={()=>onOpen(record.visit)}><Download size={15}/>Abrir</button></td></tr>;})}</tbody></table></div></>}
 </section>;
}

export default function MetricsPanel(props:{visits:Visit[];loading:boolean;onOpen:(visit:Visit)=>void;onImport:(visits:Visit[])=>Promise<void>}){
 const [view,setView]=useState<'farm'|'consolidated'>('farm');
 return <section className="metrics-area"><div className="metric-view-switch no-print" role="tablist" aria-label="Tipo de métricas"><button role="tab" aria-selected={view==='farm'} className={view==='farm'?'active':''} onClick={()=>setView('farm')}>Por finca</button><button role="tab" aria-selected={view==='consolidated'} className={view==='consolidated'?'active':''} onClick={()=>setView('consolidated')}>Consolidado de aseguramientos</button></div>{view==='farm'?<FarmMetrics visits={props.visits} loading={props.loading} onOpen={props.onOpen}/>:<ConsolidatedMetrics visits={props.visits} loading={props.loading} onImport={props.onImport}/>}</section>;
}
