'use client';
import {useEffect,useState} from 'react';
import ListPager from './list-pager';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {roleLabels,serviceLabels,canEdit,type Farm,type FarmContact,type Service} from '@/lib/team';
import {blankVisit,farmKey,metrics,type Visit} from '@/lib/model';
function Picker({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(s:string)=>void;disabled?:boolean}){return <label>{label}<Select disabled={disabled} value={value||'none'} onValueChange={s=>s&&onChange(s==='none'?'':String(s))} items={options}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
const emptyContact=():FarmContact=>({id:'',name:'',role:'',phone:'',email:'',receiveReports:true});
function ContactsEditor({value,onChange}:{value:FarmContact[];onChange:(contacts:FarmContact[])=>void}){return <div className="contacts-editor">{value.map((contact,index)=><div className="contact-card" key={contact.id||index}><div className="contact-card-heading"><strong>Contacto {index+1}</strong>{value.length>1&&<button type="button" className="secondary" onClick={()=>onChange(value.filter((_,i)=>i!==index))}>Quitar</button>}</div><div className="fields"><label>Nombre<input maxLength={300} value={contact.name} onChange={e=>onChange(value.map((c,i)=>i===index?{...c,name:e.target.value}:c))}/></label><label>Cargo<input maxLength={300} value={contact.role} onChange={e=>onChange(value.map((c,i)=>i===index?{...c,role:e.target.value}:c))}/></label><label>Teléfono<input maxLength={300} value={contact.phone} onChange={e=>onChange(value.map((c,i)=>i===index?{...c,phone:e.target.value}:c))}/></label><label>Correo<input maxLength={300} type="email" value={contact.email} onChange={e=>onChange(value.map((c,i)=>i===index?{...c,email:e.target.value}:c))}/></label></div><label className="contact-recipient"><input type="checkbox" checked={contact.receiveReports} onChange={e=>onChange(value.map((c,i)=>i===index?{...c,receiveReports:e.target.checked}:c))}/> Recibe los informes por correo</label></div>)}<button type="button" className="secondary" onClick={()=>onChange([...value,emptyContact()])}>Agregar contacto</button></div>}
export default function TeamPanel({desktop=false,mode,onFarms,onStart,visits,busy:parentBusy,openRequestId,onRequestOpened}:{desktop?:boolean;mode:'farms'|'requests';onFarms:(f:Farm[])=>void;onStart:(v:Visit)=>void;visits:Visit[];busy:boolean;openRequestId?:string;onRequestOpened?:()=>void}){
 const [person,setPerson]=useState('');
 const [page,setPage]=useState(0);
 const [farms,setFarms]=useState<Farm[]>([]),[requests,setRequests]=useState<Service[]>([]),[user,setUser]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false),[loaded,setLoaded]=useState(false);
 const [name,setName]=useState(''),[zone,setZone]=useState(''),[contacts,setContacts]=useState<FarmContact[]>([emptyContact()]),[contactDraft,setContactDraft]=useState<FarmContact[]>([]),[join,setJoin]=useState(''),[invite,setInvite]=useState(''),[inviteRole,setInviteRole]=useState('editor'),[draft,setDraft]=useState<Service|null>(null);
 const farm=farms.find(f=>f.id===selected);const manager=farm?.role==='manager';const priorVisits=farm?visits.filter(v=>v.farmId===farm.id||farmKey(v.farm)===farmKey(farm.name)).slice().sort((a,b)=>b.date.localeCompare(a.date)):[];const latestVisit=priorVisits[0];const latestMetric=latestVisit?metrics(latestVisit):null;
 async function call<T={id:string;token:string;userId:string;farms:Farm[]}>(url:string,data?:unknown){const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);const x=await r.json() as {error?:string};if(!r.ok)throw new Error(x.error||'No se pudo completar la operación.');return x as T;}
 async function refresh(){const [team,services]=await Promise.all([call('/api/team'),call<Service[]>('/api/requests')]);setFarms(team.farms);onFarms(team.farms);setUser(team.userId);setRequests(services);setLoaded(true);}
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');setFailed(false);try{await fn();}catch(e){setFailed(true);setMessage((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const timer=window.setTimeout(()=>void run(refresh));return()=>window.clearTimeout(timer);},[]);
 useEffect(()=>{if(!openRequestId||!loaded)return;const target=requests.find(request=>request.id===openRequestId),targetFarm=target?farms.find(item=>item.id===target.farmId):undefined;if(!target||!targetFarm)return;const timer=window.setTimeout(()=>{setSelected(targetFarm.id);setContactDraft(targetFarm.contacts);setPage(0);setInvite('');setDraft(target);onRequestOpened?.();},0);return()=>window.clearTimeout(timer);},[openRequestId,loaded,requests,farms,onRequestOpened]);
 function newRequest(){if(farm)setDraft({id:'',revision:0,farmId:farm.id,kind:'assurance',reason:'',date:'',rtc:'',assignee:'',status:'requested'});}
 const statuses=[{value:'requested',label:'Solicitada'},{value:'scheduled',label:'Programada'},{value:'done',label:'Realizada'},{value:'cancelled',label:'Cancelada'}];
 return <section className="followup-panel"><div className="page-heading"><div><div className="eyebrow">EQUIPO AVGUST CARE 360</div><h2>{mode==='farms'?'Directorio de fincas':'Servicios del equipo'}</h2></div><div className="actions"><button className="secondary" disabled={busy||parentBusy} onClick={()=>void run(refresh)}>Actualizar equipo</button>{mode==='farms'&&farm&&canEdit(farm.role)&&<button className="primary" disabled={busy||parentBusy} onClick={()=>onStart({...blankVisit(),farmId:farm.id,serviceKind:'assurance',farm:farm.name,zone:farm.zone,technician:farm.contacts[0]?.name||farm.contact,chapters:[1,2,3,4,5]})}>Iniciar aseguramiento</button>}</div></div>
 {message&&<p role={failed?'alert':'status'} className={'notice '+(failed?'error':'success')}>{message}</p>}
 <fieldset disabled={busy||parentBusy} style={{border:0,padding:0,minWidth:0}}>
 <div hidden={mode!=='farms'}><details><summary>Registrar una finca</summary><div className="fields"><label>Nombre de la finca<input maxLength={300} value={name} onChange={e=>setName(e.target.value)}/></label><label>Zona<input maxLength={300} value={zone} onChange={e=>setZone(e.target.value)}/></label></div><h3 className="section-gap">Contactos de la finca</h3><ContactsEditor value={contacts} onChange={setContacts}/><button className="primary section-gap" onClick={()=>void run(async()=>{const f=await call('/api/team',{op:'create',name,zone,contacts});await refresh();setSelected(f.id);setName('');setZone('');setContacts([emptyContact()]);setDraft(null);setMessage('Finca registrada. Puedes asignar participantes.');})}>Registrar finca</button></details>
 <details hidden={desktop} className="section-gap"><summary>Unirme a una finca</summary><p className="muted">Pega el código que te entregó la coordinación. Necesitas acceso a esta aplicación e iniciar sesión con tu propia cuenta.</p><label>Código de invitación<input maxLength={64} value={join} onChange={e=>setJoin(e.target.value)}/></label><button className="secondary" onClick={()=>void run(async()=>{await call('/api/team',{op:'join',token:join.trim()});setJoin('');await refresh();setMessage('Ya participas en la finca. Actualiza las visitas guardadas para consultar sus informes.');})}>Unirme</button></details>
 </div><div className="section-gap"><Picker label="Finca de trabajo" value={selected} options={[{value:'none',label:'Selecciona una finca'},...farms.map(f=>({value:f.id,label:f.name}))]} onChange={s=>{setSelected(s);setContactDraft(farms.find(f=>f.id===s)?.contacts||[]);setPage(0);setDraft(null);setInvite('');}}/></div>
 {!loaded?<p className="muted">Carga el equipo para consultar las fincas.</p>:!farms.length?<p className="empty-copy">{desktop?'Registra una finca para organizar los servicios de tu equipo.':'Registra una finca o únete con un código. Tus visitas personales están en Visitas e informes.'}</p>:null}
 {farm&&<><p>{farm.zone||'Zona sin registrar'} · {farm.contacts.map(c=>c.name).join(', ')||'Contacto sin registrar'}</p><p className="muted">{desktop?'Los participantes son nombres para asignar tareas. Esta edición no usa cuentas ni controla accesos.':`Tu permiso: ${roleLabels[farm.role]}. Las visitas vinculadas a esta finca se comparten con sus participantes.`}</p>{latestVisit&&<div className="notice farm-last-visit"><strong>Último informe: {latestVisit.date}</strong><span>{latestVisit.reviewed?'Revisado':'Borrador'} · {latestMetric?.score===null?'sin medición':`${latestMetric?.score}%`} · {latestMetric?.findings||0} hallazgo{latestMetric?.findings===1?'':'s'} · {priorVisits.length} visita{priorVisits.length===1?'':'s'} en el historial</span></div>}<div hidden={mode!=='farms'}><h3 className="section-gap">Contactos e informes</h3>{manager?<><ContactsEditor value={contactDraft} onChange={setContactDraft}/><button className="primary section-gap" onClick={()=>void run(async()=>{await call('/api/team',{op:'contacts',farmId:farm.id,contacts:contactDraft});await refresh();setContactDraft(contactDraft);setMessage('Contactos actualizados.');})}>Guardar contactos</button></>:<div className="contact-list">{farm.contacts.map(c=><p key={c.id}><strong>{c.name}</strong> · {c.role}<br/>{c.phone} · {c.email}{c.receiveReports?' · Recibe informes':''}</p>)}</div>}<h3 className="section-gap">Participantes</h3>{desktop&&<div className="fields"><label>Nombre del participante<input maxLength={300} value={person} onChange={e=>setPerson(e.target.value)}/></label><button className="secondary" onClick={()=>void run(async()=>{await call('/api/team',{op:'addLocal',farmId:farm.id,name:person});setPerson('');await refresh();setMessage('Participante agregado.');})}>Agregar participante</button></div>}
 {farm.members.map(m=><div className="visit-row" key={m.user_id}><div><strong>{m.name}</strong><small>{desktop?'Participante local':roleLabels[m.role]}{!desktop&&m.user_id===farm.owner?' · Creador de la finca':''}</small></div>{!desktop&&manager&&m.user_id!==farm.owner&&m.user_id!==user&&<Picker label={`Permiso de ${m.name}`} value={m.role} options={[...Object.entries(roleLabels).map(([value,label])=>({value,label})),{value:'remove',label:'Retirar de la finca'}]} onChange={role=>void run(async()=>{await call('/api/team',{op:'member',farmId:farm.id,userId:m.user_id,role});await refresh();setMessage('Permisos actualizados.');})}/>}</div>)}
 {!desktop&&manager&&<div className="section-gap"><Picker label="Permiso de la invitación" value={inviteRole} options={Object.entries(roleLabels).map(([value,label])=>({value,label}))} onChange={setInviteRole}/><button className="secondary" onClick={()=>void run(async()=>{const x=await call('/api/team',{op:'invite',farmId:farm.id,role:inviteRole});setInvite(x.token);})}>Generar código de invitación</button>{invite&&<div className="notice"><p>Código de un solo uso, válido durante 24 horas. Compártelo solo con la persona que quieres incorporar.</p><input aria-label="Código para compartir" readOnly value={invite}/><button className="secondary" onClick={()=>void run(async()=>{await call('/api/team',{op:'revokeInvite',farmId:farm.id,token:invite});setInvite('');setMessage('Código cancelado.');})}>Cancelar código</button></div>}</div>}
 </div><div hidden={mode!=='requests'}><div className="page-heading section-gap"><h3>Solicitudes de servicio</h3>{canEdit(farm.role)&&<button className="primary" onClick={newRequest}>Nueva solicitud</button>}</div>
 <div hidden={Boolean(draft)}>{requests.filter(r=>r.farmId===farm.id).slice(page*8,page*8+8).map(r=><div className="visit-row" key={r.id}><div><strong>{serviceLabels[r.kind]} · {r.date||'Sin fecha'}</strong><small>{statuses.find(s=>s.value===r.status)?.label} · {farm.members.find(m=>m.user_id===r.assignee)?.name||'Sin profesional asignado'}</small><p>{r.reason}</p></div><button className="secondary" onClick={()=>setDraft(r)}>{canEdit(farm.role)?'Abrir solicitud':'Consultar solicitud'}</button></div>)}
 {!requests.some(r=>r.farmId===farm.id)&&<p className="empty-copy">No hay solicitudes para esta finca.</p>}
 <ListPager page={page} total={requests.filter(r=>r.farmId===farm.id).length} onChange={setPage}/></div>{draft&&<div className="action-editor"><h3>{draft.id?'Editar solicitud':'Nueva solicitud'}</h3><div className="fields"><Picker label="Tipo de servicio" value={draft.kind} options={Object.entries(serviceLabels).map(([value,label])=>({value,label}))} onChange={s=>setDraft({...draft,kind:s as Service['kind']})}/><label>Fecha propuesta<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><Picker label="Representante técnico comercial" value={draft.rtc} disabled={!manager} options={[{value:'none',label:'Sin asignar'},...farm.members.filter(m=>canEdit(m.role)).map(m=>({value:m.user_id,label:m.name}))]} onChange={s=>setDraft({...draft,rtc:s})}/><Picker label="Profesional que realiza el servicio" value={draft.assignee} disabled={!manager} options={[{value:'none',label:'Sin asignar'},...farm.members.filter(m=>canEdit(m.role)).map(m=>({value:m.user_id,label:m.name}))]} onChange={s=>setDraft({...draft,assignee:s})}/><Picker label="Estado de la solicitud" value={draft.status} options={statuses} onChange={s=>setDraft({...draft,status:s as Service['status']})}/></div><label>Motivo / actividad solicitada<textarea maxLength={3000} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><div className="actions"><button className="primary" onClick={()=>void run(async()=>{const r=await call<Service>('/api/requests',draft);setDraft(r);await refresh();setMessage('Solicitud guardada.');})}>Guardar solicitud</button><button className="secondary" onClick={()=>setDraft(null)}>Cerrar</button></div>
 {draft.id&&draft.status!=='cancelled'&&<button className="secondary section-gap" onClick={()=>void run(async()=>{const r:Service=await call('/api/requests',draft);await refresh();setDraft(r);onStart({...blankVisit(),farmId:farm.id,requestId:r.id,serviceKind:r.kind,chapters:r.kind==='assurance'?[1,2,3,4,5]:[],farm:farm.name,zone:farm.zone,technician:farm.contacts[0]?.name||farm.contact,rtc:farm.members.find(m=>m.user_id===r.rtc)?.name||'',responsible:farm.members.find(m=>m.user_id===r.assignee)?.name||'',date:r.date||blankVisit().date,conclusion:`${serviceLabels[r.kind]}: ${r.reason}`});})}>Crear informe de esta solicitud</button>}</div>}
 </div></>}
 </fieldset></section>;
}
