import {download} from './export-word';
import type {ConsolidatedMetricAnalysis} from './metric-analysis';

const encoder=new TextEncoder();
const xml=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]!));
const column=(index:number)=>{let value='';for(let n=index;n>=0;n=Math.floor(n/26)-1)value=String.fromCharCode(65+n%26)+value;return value;};
const crcTable=(()=>{const table=new Uint32Array(256);for(let i=0;i<256;i++){let c=i;for(let bit=0;bit<8;bit++)c=c&1?0xedb88320^(c>>>1):c>>>1;table[i]=c>>>0;}return table;})();
const crc32=(bytes:Uint8Array)=>{let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;};
const u16=(value:number)=>Uint8Array.of(value&255,value>>>8&255);
const u32=(value:number)=>Uint8Array.of(value&255,value>>>8&255,value>>>16&255,value>>>24&255);
const join=(parts:Uint8Array[])=>{const bytes=new Uint8Array(parts.reduce((total,part)=>total+part.length,0));let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}return bytes;};
function zip(files:{name:string;data:string}[]){
 let offset=0;const local:Uint8Array[]=[],central:Uint8Array[]=[];
 for(const file of files){const name=encoder.encode(file.name),data=encoder.encode(file.data),crc=crc32(data);const header=join([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]);local.push(header,data);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=header.length+data.length;}
 const directory=join(central);return join([...local,directory,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(directory.length),u32(offset),u16(0)]);
}
function style(value:string,rowIndex:number,columnIndex:number,sheet:string){if(sheet==='Resumen')return rowIndex===0?2:columnIndex===0?3:4;if(rowIndex===0)return 1;if(sheet==='Matriz histórica'&&columnIndex===6)return value==='SI'?5:value==='NO'?6:7;if(rowIndex%2===0)return 8;return 0;}
function worksheet(rows:string[][],sheet:string){const cells=rows.map((row,rowIndex)=>`<row r="${rowIndex+1}">${row.map((value,columnIndex)=>`<c r="${column(columnIndex)}${rowIndex+1}" t="inlineStr" s="${style(value,rowIndex,columnIndex,sheet)}"><is><t xml:space="preserve">${xml(value)}</t></is></c>`).join('')}</row>`).join('');const columns=rows[0]?.map((_,index)=>`<col min="${index+1}" max="${index+1}" width="${sheet==='Matriz histórica'&&index>4?40:index<3?22:30}" customWidth="1"/>`).join('')||'';const filter=sheet==='Resumen'?'':`<autoFilter ref="A1:${column(Math.max((rows[0]?.length||1)-1,0))}${rows.length}"/>`;return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${columns}</cols><sheetData>${cells}</sheetData>${filter}</worksheet>`;}

export async function exportConsolidatedMatrixExcel(data:ConsolidatedMetricAnalysis,generatedAt=new Date().toISOString().slice(0,10)){
 const summary=[['AVGUST CARE 360 · Consolidado de aseguramientos',''],['Fecha de generación',generatedAt],['Aseguramientos revisados',String(data.records.length)],['Fincas evaluadas',String(data.farms)],['Criterios aplicables',String(data.applicable)],['Hallazgos (respuestas No)',String(data.findings)],['Indicador consolidado',data.score===null?'Sin medición':`${data.score}%`]];
 const chapters=[['Capítulo','Criterios aplicables','Hallazgos','Indicador','Fincas evaluadas'],...data.chapters.map(c=>[`${c.id}. ${c.title}`,String(c.applicable),String(c.findings),c.score===null?'Sin medición':`${c.score}%`,String(c.farms)])];
 const items=[['Ítem','Capítulo','Descripción','Evaluaciones','Hallazgos','% con inconveniente','Fincas'],...data.items.map(item=>[item.id,`${item.chapter}. ${item.chapterTitle}`,item.text,String(item.applicable),String(item.findings),`${item.rate}%`,String(item.farms)])];
 const matrix=[['Finca','Fecha','Responsable AVGUST','Capítulo','Ítem','Criterio','Respuesta','Hallazgo / observación','Recomendación'],...data.matrix.map(row=>[row.farm,row.date,row.responsible,row.chapter,row.item,row.text,row.answer,row.observation,row.recommendation])];
 const sheets=[['Resumen',summary],['Por capítulo',chapters],['Ítems críticos',items],['Matriz histórica',matrix]] as const;
 const files=[
  {name:'[Content_Types].xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`},
  {name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},
  {name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([name],i)=>`<sheet name="${xml(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`},
  {name:'xl/_rels/workbook.xml.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`},
  {name:'xl/styles.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="11"/><color rgb="FF334F58"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font><font><b/><color rgb="FF007FA3"/><sz val="16"/><name val="Arial"/></font></fonts><fills count="9"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF007FA3"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE9F7FB"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE7F5DF"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF7E3"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFDE7E5"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF1F4F5"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF7FBFC"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFDDE7E8"/></left><right style="thin"><color rgb="FFDDE7E8"/></right><top style="thin"><color rgb="FFDDE7E8"/></top><bottom style="thin"><color rgb="FFDDE7E8"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="1" fillId="3" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="1" fillId="4" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="0" fillId="5" borderId="1" xfId="0" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="0" fillId="6" borderId="1" xfId="0" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="0" fillId="7" borderId="1" xfId="0" applyFill="1" applyBorder="1"/><xf numFmtId="0" fontId="0" fillId="8" borderId="1" xfId="0" applyFill="1" applyBorder="1"/></cellXfs></styleSheet>'},
  ...sheets.map(([name,rows],i)=>({name:`xl/worksheets/sheet${i+1}.xml`,data:worksheet(rows,name)}))
 ];
 await download(new Blob([zip(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`AVGUST CARE 360 - Matriz consolidada - ${generatedAt}.xlsx`);
}
