import {Document,HeadingLevel,Packer,Paragraph,Table,TableCell,TableRow,TextRun,WidthType} from 'docx';
import {download} from './export-word';
import {metricStatusLabels,metricTrendLabels} from './model';
import type {ConsolidatedMetricAnalysis} from './metric-analysis';

export async function exportConsolidatedWord(data:ConsolidatedMetricAnalysis,period:string){
 const children:(Paragraph|Table)[]=[];const text=(value:string)=>children.push(new Paragraph({children:[new TextRun(value)],spacing:{after:120}}));const heading=(value:string,level:typeof HeadingLevel.HEADING_1|typeof HeadingLevel.HEADING_2=HeadingLevel.HEADING_1)=>children.push(new Paragraph({text:value,heading:level,keepNext:true,spacing:{before:240,after:120}}));const table=(rows:string[][])=>children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:rows.map(row=>new TableRow({children:row.map(value=>new TableCell({children:[new Paragraph(value)],margins:{top:100,bottom:100,left:120,right:120}}))}))}));
 children.push(new Paragraph({text:'AVGUST CARE 360',heading:HeadingLevel.TITLE}));text('AVGUST Crop Protection · Consolidado de aseguramientos');heading('Informe técnico consolidado');text(`Periodo: ${period||'Histórico seleccionado'}`);text(`Indicador consolidado: ${data.score===null?'Sin medición':`${data.score}% · ${metricStatusLabels[data.status]}`}.`);text(`Comportamiento: ${metricTrendLabels[data.trend]}. ${data.farms} fincas y ${data.records.length} aseguramientos revisados.`);
 heading('Hallazgos por capítulo');table([['Capítulo','Hallazgos','Criterios aplicables','Indicador','Fincas'],...data.chapters.map(c=>[`${c.id}. ${c.title}`,String(c.findings),String(c.applicable),c.score===null?'Sin medición':`${c.score}%`,String(c.farms)])]);heading('Ítems prioritarios');table([['Ítem','Capítulo','Hallazgos','Frecuencia','Descripción'],...data.items.filter(i=>i.findings>0).slice(0,15).map(i=>[i.id,`${i.chapter}. ${i.chapterTitle}`,String(i.findings),`${i.rate}%`,i.text])]);heading('Tendencia');table([['Periodo','Indicador','Hallazgos','Aseguramientos'],...data.timeline.map(t=>[t.period,`${t.score}%`,String(t.findings),String(t.reports)])]);
 const doc=new Document({creator:'AVGUST CARE 360',title:'Consolidado de aseguramientos',styles:{default:{document:{run:{font:'Arial',size:22,color:'172D31'},paragraph:{spacing:{after:120,line:276}}},title:{run:{font:'Arial',size:36,bold:true,color:'007FA3'}},heading1:{run:{font:'Arial',size:28,bold:true,color:'172D31'}},heading2:{run:{font:'Arial',size:24,bold:true,color:'172D31'}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1020,bottom:1020,left:1020,right:1020}}},children}]});await download(await Packer.toBlob(doc),`AVGUST CARE 360 - Consolidado ${period||'histórico'}.docx`);
}
