import {catalog,farmKey,type Answer,type Visit} from './model';

export type MatrixImport={visits:Visit[];errors:string[];rows:number};
const clean=(value:string)=>value.trim().toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ');
const required=['finca','fecha','capitulo','item','respuesta'];
const findColumn=(headers:string[],name:string)=>headers.findIndex(header=>clean(header)===name||clean(header).includes(name));
const answerValue=(value:string)=>{const key=clean(value);return key==='si'||key==='sí'?'SI':key==='no'?'NO':key==='no aplica'||key==='na'?'NA':'';};

export function matrixRowsToVisits(rows:string[][]):MatrixImport{
 if(!rows.length)return {visits:[],errors:['El archivo no contiene filas.'],rows:0};
 const headers=rows[0].map(String);const columns=Object.fromEntries([...required,'responsable avgust','hallazgo observacion','recomendacion'].map(name=>[name,findColumn(headers,name)]));
 const missing=required.filter(name=>columns[name]<0);if(missing.length)return {visits:[],errors:[`Faltan columnas: ${missing.join(', ')}.`],rows:rows.length-1};
 const groups=new Map<string,{farm:string;date:string;responsible:string;chapters:Set<number>;answers:Record<string,Answer>;rows:number[]}>();const errors:string[]=[];
 rows.slice(1).forEach((row,index)=>{const rowNumber=index+2;const get=(name:string)=>columns[name]>=0?String(row[columns[name]]||'').trim():'';const farm=get('finca'),date=get('fecha'),item=get('item'),answer=answerValue(get('respuesta')),chapter=Number((get('capitulo').match(/^\s*(\d+)/)||['','0'])[1]);if(!farm&&!date&&!item)return;if(!farm||!date||!item||!answer){errors.push(`Fila ${rowNumber}: completa finca, fecha, ítem y respuesta.`);return;}const question=catalog.flatMap(c=>c.items).find(q=>q.id===item);if(!question||!chapter||Number(item.split('.')[0])!==chapter){errors.push(`Fila ${rowNumber}: el ítem ${item} no corresponde al capítulo indicado.`);return;}const responsible=get('responsable avgust')||'Histórico importado';const key=`${farmKey(farm)}|${date}|${farmKey(responsible)}`;const group=groups.get(key)||{farm,date,responsible,chapters:new Set<number>(),answers:{},rows:[]};if(group.answers[item]){errors.push(`Fila ${rowNumber}: el ítem ${item} está repetido para ${farm} del ${date}.`);return;}group.chapters.add(chapter);group.answers[item]={value:answer,observation:get('hallazgo observacion'),recommendation:get('recomendacion')};group.rows.push(rowNumber);groups.set(key,group);});
 const visits:Visit[]=[];
 for(const group of groups.values()){for(const chapter of group.chapters){for(const question of catalog.find(c=>c.id===chapter)?.items||[]){const answer=group.answers[question.id];if(!answer)errors.push(`${group.farm} · ${group.date}: falta el ítem ${question.id}.`);else if(answer.value==='NO'&&(!answer.observation||!answer.recommendation))errors.push(`${group.farm} · ${group.date}: el ítem ${question.id} requiere hallazgo y recomendación.`);}}
  visits.push({id:'',revision:0,serviceKind:'assurance',farm:group.farm,date:group.date,city:'',zone:'',technician:'Importación histórica',responsible:group.responsible,rtc:'',chapters:[...group.chapters].sort((a,b)=>a-b),answers:group.answers,notes:{},recommendations:{},measurements:{},delivery:'',followup:'',conclusion:'Aseguramiento importado desde matriz histórica.',photos:[],reviewed:true,actions:{}});
 }
 return {visits:errors.length?[]:visits,errors,rows:rows.length-1};
}

function csv(text:string){const firstLine=text.split(/\r?\n/,1)[0]||'';const delimiter=(firstLine.match(/;/g)||[]).length>(firstLine.match(/,/g)||[]).length?';':',';const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i],next=text[i+1];if(char==='"'&&quoted&&next==='"'){value+='"';i++;continue;}if(char==='"'){quoted=!quoted;continue;}if(char===delimiter&&!quoted){row.push(value);value='';continue;}if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(value);if(row.some(cell=>cell.trim()))rows.push(row);row=[];value='';continue;}value+=char;}row.push(value);if(row.some(cell=>cell.trim()))rows.push(row);return rows;}
async function unzip(file:File){const bytes=new Uint8Array(await file.arrayBuffer());const entries=new Map<string,Uint8Array>();for(let i=0;i<=bytes.length-46;i++){if(bytes[i]!==80||bytes[i+1]!==75||bytes[i+2]!==1||bytes[i+3]!==2)continue;const method=bytes[i+10]|bytes[i+11]<<8,compressed=bytes[i+20]|bytes[i+21]<<8|bytes[i+22]<<16|bytes[i+23]<<24,nameLength=bytes[i+28]|bytes[i+29]<<8,extraLength=bytes[i+30]|bytes[i+31]<<8,commentLength=bytes[i+32]|bytes[i+33]<<8,localOffset=bytes[i+42]|bytes[i+43]<<8|bytes[i+44]<<16|bytes[i+45]<<24,name=new TextDecoder().decode(bytes.slice(i+46,i+46+nameLength));const localName=bytes[localOffset+26]|bytes[localOffset+27]<<8,localExtra=bytes[localOffset+28]|bytes[localOffset+29]<<8,data=bytes.slice(localOffset+30+localName+localExtra,localOffset+30+localName+localExtra+compressed);if(method===0)entries.set(name,data);else if(method===8&&typeof DecompressionStream!=='undefined'){const safeBuffer=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength) as ArrayBuffer;const stream=new Blob([safeBuffer]).stream().pipeThrough(new DecompressionStream('deflate-raw'));entries.set(name,new Uint8Array(await new Response(stream).arrayBuffer()));}else throw new Error('El archivo Excel usa una compresión no compatible en este equipo. Guarda una copia como CSV e impórtala.');i+=46+nameLength+extraLength+commentLength-1;}return entries;}
function xmlRows(entries:Map<string,Uint8Array>){const decode=(name:string)=>new TextDecoder().decode(entries.get(name)||new Uint8Array());const parse=(text:string)=>new DOMParser().parseFromString(text,'application/xml');const shared=parse(decode('xl/sharedStrings.xml')).getElementsByTagName('si');const strings=Array.from(shared).map(node=>node.textContent||'');const book=parse(decode('xl/workbook.xml'));const rels=parse(decode('xl/_rels/workbook.xml.rels'));const sheet=Array.from(book.getElementsByTagName('sheet')).find(node=>clean(node.getAttribute('name')||'')==='matriz historica')||book.getElementsByTagName('sheet')[0];if(!sheet)throw new Error('No se encontró una hoja en el archivo.');const relation=Array.from(rels.getElementsByTagName('Relationship')).find(node=>node.getAttribute('Id')===sheet.getAttribute('r:id'));const target=relation?.getAttribute('Target');if(!target)throw new Error('No se encontró la hoja histórica.');const document=parse(decode(`xl/${target.replace(/^\//,'')}`));return Array.from(document.getElementsByTagName('row')).map(row=>{const values:string[]=[];Array.from(row.getElementsByTagName('c')).forEach(cell=>{const ref=cell.getAttribute('r')||'A1',letters=(ref.match(/[A-Z]+/)||['A'])[0];let column=0;for(const letter of letters)column=column*26+letter.charCodeAt(0)-64;const raw=cell.getElementsByTagName('v')[0]?.textContent||cell.getElementsByTagName('t')[0]?.textContent||'';values[column-1]=cell.getAttribute('t')==='s'?strings[Number(raw)]||'':raw;});return values.map(value=>value||'');});}

export async function readMatrixFile(file:File){if(file.name.toLocaleLowerCase().endsWith('.csv'))return csv(await file.text());if(!file.name.toLocaleLowerCase().endsWith('.xlsx'))throw new Error('Selecciona una matriz Excel .xlsx o un archivo CSV.');return xmlRows(await unzip(file));}
