import {doc, setDoc, collection, getDocs, query, where, updateDoc} from 'firebase/firestore';
import {db, auth} from './firebase';

export type FarmInvitation = {
  id: string;
  code: string;
  token: string;
  farm: string;
  farmId?: string;
  clientName: string;
  clientRole?: string;
  clientEmail?: string;
  clientPhone?: string;
  status: 'active' | 'revoked';
  createdAt: string;
  createdBy: string;
  expiresAt?: string;
};

const LOCAL_STORAGE_KEY = 'care360:invitations';
const ACTIVE_SESSION_KEY = 'care360:client_session';

function getLocalInvitations(): FarmInvitation[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveLocalInvitations(list: FarmInvitation[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(list));
  } catch {}
}

/**
 * Generates an easy-to-read invitation code (e.g. MIPE-8429)
 */
export function generateInvitationCode(): string {
  const num = Math.floor(1000 + Math.random() * 9000);
  return `MIPE-${num}`;
}

/**
 * Generates a random secure token
 */
export function generateToken(): string {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID().replace(/-/g, '').slice(0, 16);
  }
  return Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);
}

/**
 * Creates a new invitation for a farm administrator / client
 */
export async function createFarmInvitation(input: {
  farm: string;
  farmId?: string;
  clientName: string;
  clientRole?: string;
  clientEmail?: string;
  clientPhone?: string;
  createdBy?: string;
}): Promise<FarmInvitation> {
  const code = generateInvitationCode();
  const token = generateToken();
  const id = `inv_${Date.now()}_${token.slice(0, 6)}`;
  const author = input.createdBy || auth.currentUser?.email || 'Técnico Agrícola AVGUST';

  const invitation: FarmInvitation = {
    id,
    code,
    token,
    farm: input.farm,
    farmId: input.farmId,
    clientName: input.clientName,
    clientRole: input.clientRole || 'Responsable de Finca',
    clientEmail: input.clientEmail,
    clientPhone: input.clientPhone,
    status: 'active',
    createdAt: new Date().toISOString(),
    createdBy: author
  };

  // 1. Save locally for instant availability
  const current = getLocalInvitations();
  saveLocalInvitations([invitation, ...current.filter(i => i.id !== id)]);

  // 2. Persist to Firestore
  try {
    const docRef = doc(db, 'invitations', id);
    await setDoc(docRef, invitation, {merge: true});
  } catch (err) {
    console.warn('Could not persist invitation to Firestore, cached locally:', err);
  }

  return invitation;
}

/**
 * Verifies an invitation either by token (from URL) or by manual code (e.g. MIPE-1234)
 */
export async function verifyFarmInvitation(tokenOrCode: string): Promise<FarmInvitation | null> {
  const cleaned = tokenOrCode.trim().toUpperCase();
  if (!cleaned) return null;

  // 1. Check local cache first
  const localList = getLocalInvitations();
  const foundLocal = localList.find(
    i => (i.code.toUpperCase() === cleaned || i.token.toUpperCase() === cleaned || i.token === tokenOrCode.trim()) && i.status === 'active'
  );
  if (foundLocal) return foundLocal;

  // 2. Query Firestore by code or by token
  try {
    const colRef = collection(db, 'invitations');
    // Try by code
    const qCode = query(colRef, where('code', '==', cleaned));
    const snapCode = await getDocs(qCode);
    if (!snapCode.empty) {
      const inv = snapCode.docs[0].data() as FarmInvitation;
      if (inv.status === 'active') {
        saveLocalInvitations([inv, ...localList.filter(i => i.id !== inv.id)]);
        return inv;
      }
    }

    // Try by token
    const qToken = query(colRef, where('token', '==', tokenOrCode.trim()));
    const snapToken = await getDocs(qToken);
    if (!snapToken.empty) {
      const inv = snapToken.docs[0].data() as FarmInvitation;
      if (inv.status === 'active') {
        saveLocalInvitations([inv, ...localList.filter(i => i.id !== inv.id)]);
        return inv;
      }
    }
  } catch (err) {
    console.warn('Error verifying invitation against Firestore:', err);
  }

  return null;
}

/**
 * Lists all invitations generated by technicians
 */
export async function listFarmInvitations(): Promise<FarmInvitation[]> {
  const localList = getLocalInvitations();
  try {
    const colRef = collection(db, 'invitations');
    const snapshot = await getDocs(colRef);
    const cloudList: FarmInvitation[] = [];
    snapshot.forEach(d => {
      cloudList.push(d.data() as FarmInvitation);
    });
    // Merge cloud and local
    const map = new Map<string, FarmInvitation>();
    for (const inv of localList) map.set(inv.id, inv);
    for (const inv of cloudList) map.set(inv.id, inv);
    const merged = Array.from(map.values()).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    saveLocalInvitations(merged);
    return merged;
  } catch {
    return localList;
  }
}

/**
 * Revokes an invitation immediately
 */
export async function revokeFarmInvitation(id: string): Promise<void> {
  const localList = getLocalInvitations();
  saveLocalInvitations(localList.map(i => (i.id === id ? {...i, status: 'revoked' as const} : i)));

  try {
    const docRef = doc(db, 'invitations', id);
    await updateDoc(docRef, {status: 'revoked'});
  } catch (err) {
    console.warn('Error revoking invitation in Firestore:', err);
  }
}

/**
 * Stores the authenticated farm manager session in local storage
 */
export function setClientSession(invitation: FarmInvitation): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(ACTIVE_SESSION_KEY, JSON.stringify(invitation));
  } catch {}
}

/**
 * Retrieves the current authenticated farm manager session
 */
export function getClientSession(): FarmInvitation | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = localStorage.getItem(ACTIVE_SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

/**
 * Clears the active farm manager session
 */
export function clearClientSession(): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.removeItem(ACTIVE_SESSION_KEY);
  } catch {}
}

/**
 * Builds the URL to access the farm portal with the invitation token
 */
export function buildInvitationPortalUrl(token: string): string {
  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  return `${origin}?portal=finca&invitation=${encodeURIComponent(token)}`;
}

/**
 * Formats a ready-to-send WhatsApp invitation message
 */
export function buildWhatsAppInvitationMessage(invitation: FarmInvitation): string {
  const url = buildInvitationPortalUrl(invitation.token);
  return `*AVGUST CARE 360 · Servidor en Línea de Informes MIPE*

Estimado(a) *${invitation.clientName}*,
El equipo técnico de AVGUST te ha habilitado acceso exclusivo al servidor en línea de aseguramientos para la finca *${invitation.farm}*.

🔑 *Código de Acceso:* ${invitation.code}
🔗 *Enlace directo:*
${url}

En este portal podrás:
• Consultar el semáforo y estatus oficial MIPE (Saludable ≥95%, Aceptable 85-94%, Crítico <85%)
• Ver la evolución de todas las visitas técnicas sin imprimir papel
• Revisar las recomendaciones y compromisos acordados
• Descargar los informes en Word o PDF

_AVGUST Crop Protection · Juntos Crecemos Bien_`;
}
