import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const visits=sqliteTable('visits',{id:text('id').primaryKey(),owner:text('owner').notNull(),farmId:text('farm_id'),farm:text('farm').notNull(),date:text('date').notNull(),payload:text('payload').notNull(),revision:integer('revision').notNull().default(1),updated:text('updated').notNull()},t=>[index('idx_visits_owner_date').on(t.owner,t.date),index('idx_visits_farm_date').on(t.farmId,t.date)]);
export const photos=sqliteTable('photos',{id:text('id').primaryKey(),owner:text('owner').notNull(),farmId:text('farm_id'),key:text('key').notNull(),mime:text('mime').notNull()},t=>[index('idx_photos_owner').on(t.owner),index('idx_photos_farm').on(t.farmId)]);

export const farms=sqliteTable('farms',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),zone:text('zone').notNull(),contact:text('contact').notNull()});
export const members=sqliteTable('farm_members',{farmId:text('farm_id').notNull(),userId:text('user_id').notNull(),name:text('name').notNull(),role:text('role').notNull()},t=>[primaryKey({columns:[t.farmId,t.userId]}),index('idx_members_user').on(t.userId)]);
export const invitations=sqliteTable('farm_invitations',{token:text('token').primaryKey(),farmId:text('farm_id').notNull(),role:text('role').notNull(),expires:text('expires').notNull()});
export const requests=sqliteTable('service_requests',{id:text('id').primaryKey(),farmId:text('farm_id').notNull(),owner:text('owner').notNull(),revision:integer('revision').notNull(),payload:text('payload').notNull()},t=>[index('idx_requests_farm').on(t.farmId)]);
export const contacts=sqliteTable('farm_contacts',{id:text('id').primaryKey(),farmId:text('farm_id').notNull(),name:text('name').notNull(),role:text('role').notNull(),phone:text('phone').notNull(),email:text('email').notNull(),receiveReports:integer('receive_reports').notNull().default(0)},t=>[index('idx_contacts_farm').on(t.farmId)]);
export const auditEvents=sqliteTable('audit_events',{id:text('id').primaryKey(),farmId:text('farm_id').notNull(),actorId:text('actor_id').notNull(),event:text('event').notNull(),subjectType:text('subject_type').notNull(),subjectId:text('subject_id').notNull(),details:text('details').notNull(),created:text('created').notNull()},t=>[index('idx_audit_events_farm_created').on(t.farmId,t.created)]);
export const reportVersions=sqliteTable('report_versions',{id:text('id').primaryKey(),farmId:text('farm_id').notNull(),visitId:text('visit_id').notNull(),versionNumber:integer('version_number').notNull(),status:text('status').notNull(),sourceVisitRevision:integer('source_visit_revision').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),submittedBy:text('submitted_by'),submittedAt:text('submitted_at'),approvedBy:text('approved_by'),approvedAt:text('approved_at'),publishedBy:text('published_by'),publishedAt:text('published_at'),snapshotJson:text('snapshot_json'),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[index('idx_report_versions_farm_created').on(t.farmId,t.createdAt),index('idx_report_versions_visit_status').on(t.visitId,t.status)]);
